set data_date = '2026-5-4';
set start_date = '2026-4-8';
use schema mkt_sponsored_ads_sandbox;

create or replace local temp table tmp_custom_exp_readout_step_1 as
SELECT
    $data_date AS data_date
    --EXP_USER_ID, DEVICE_CATEGORY_VISITOR,
    , 'ALL' as groupingset, A.EXPERIMENT, A.VARIATION, A.EXP_USER_ID

    /** auth metrics coming from ms_session_account_auth_metrics not yet in VW_EXP_SESSION_METRICS **/
    , sum(total_searches) as total_searches
    , sum(reformulation_searches)  as reformulation_searches
    , sum(reform_different_keyword_searches)  as reform_different_keyword_searches
    , sum(autocomplete_searches) as autocomplete_searches
    , sum(autocomplete_searches_with_purchase) as autocomplete_searches_with_purchase
    , sum(searches_with_product_engagement)  as searches_with_product_engagement
    , sum(searches_with_product_click)  as searches_with_product_click
    , sum(searches_with_addtocart_click) as searches_with_addtocart_click
    , sum(searches_with_addtoautoship_click)  as searches_with_addtoautoship_click
    , sum(null_result_searches) as null_result_searches
    , sum(searches_with_no_product_engagement) as searches_with_no_product_engagement
    , sum(exit_searches) as exit_searches
    , sum(searches_with_purchase) as searches_with_purchase
    , sum(searches_with_purchase_multi_touch) as searches_with_purchase_multi_touch
    , sum(addtoautoship_searches_with_purchase) as addtoautoship_searches_with_purchase
    , sum(addtonewautoship_searches_with_purchase) as addtonewautoship_searches_with_purchase
    , sum(addtoexistautoship_searches_with_purchase) as addtoexistautoship_searches_with_purchase
    , sum(addtoautoship_searches_with_purchase_multi_touch) as addtoautoship_searches_with_purchase_multi_touch
    , sum(addtonewautoship_searches_with_purchase_multi_touch) as addtonewautoship_searches_with_purchase_multi_touch
    , sum(addtoexistautoship_searches_with_purchase_multi_touch) as addtoexistautoship_searches_with_purchase_multi_touch
    , sum(click_reciprocal_rank) as click_reciprocal_rank
    , sum(multilevel_ndcg) as multilevel_ndcg
    , count(distinct s.session_id) as total_search_sessions
    , count(distinct case when s.session_has_purchase_flag = 1 then s.session_id end) as search_session_with_purchase_multi_touch
    , sum(attributed_multi_touch_revenue) as attributed_multi_touch_revenue
    , sum(attributed_last_touch_revenue) as attributed_last_touch_revenue
FROM ecom_sandbox.ms_exp_sessions_base a
-- JOIN ecom_sandbox.exp_active_experiments b
--     ON a.experiment=b.experiment
--         AND a.session_date >=b.start_date
--         AND a.session_date <= $data_date
--         AND b.data_date=$data_date
JOIN discovery_sandbox.prd_f_d_expr_search_metrics_optimizely s
    ON a.session_date = s.session_date
        AND a.session_id = s.session_id
where 1=1
    and a.experiment = '2026_04_DISCOVERY_SEARCH_REDIRECT_REMOVALS'
    and a.session_date >= $start_date
    and a.session_id in (
        select distinct session_id from discovery_sandbox.prd_f_d_expr_search_metrics_optimizely
        where session_date >= $start_date
            and search_term in (select distinct search_term from tmp_brand_redirect_search_terms))
GROUP BY ALL
order by 3;




create or replace local temporary table TEMP_TEST_METRICS_level_1 as
with visitor_counts as (
    select data_date, experiment, variation,
        count(distinct exp_user_id) as visitorcount
    from tmp_custom_exp_readout_step_1
    group by data_date, experiment, variation
)
select
  $data_date  data_date
    , 'ALL' as groupingset_name
    , m.EXPERIMENT
    , m.VARIATION
    , max(v.visitorcount) as visitor_count
    , COALESCE(DIV0NULL(sum(m.REFORMULATION_SEARCHES),visitor_count), 0) as AVG_REFORMULATION_SEARCHES
    , COALESCE(DIV0NULL(sum(m.TOTAL_SEARCHES),visitor_count), 0) as AVG_TOTAL_SEARCHES
    , sum(m.REFORMULATION_SEARCHES) as SUM_REFORMULATION_SEARCHES
    , sum(m.TOTAL_SEARCHES) as SUM_TOTAL_SEARCHES
    , count(distinct m.REFORMULATION_SEARCHES) as COUNT_DISTINCT_REFORMULATION_SEARCHES
    , count(distinct m.TOTAL_SEARCHES) as COUNT_DISTINCT_TOTAL_SEARCHES
    , case when visitor_count > 1 then (sum(power(m.REFORMULATION_SEARCHES,2)) - (visitor_count * power((sum(m.REFORMULATION_SEARCHES) / visitor_count),2))) / (visitor_count - 1) else 0 end  as VARIANCE_REFORMULATION_SEARCHES
    , case when visitor_count > 1 then (sum(power(m.TOTAL_SEARCHES,2)) - (visitor_count * power((sum(m.TOTAL_SEARCHES) / visitor_count),2))) / (visitor_count - 1) else 0 end  as VARIANCE_TOTAL_SEARCHES
    , case when visitor_count > 1 then (sum(m.REFORMULATION_SEARCHES * m.TOTAL_SEARCHES) - (visitor_count * (sum(m.REFORMULATION_SEARCHES) / visitor_count) * (sum(m.TOTAL_SEARCHES) / visitor_count))) / (visitor_count - 1) else 0 end as COV_RE_SEARCH_RATE
    , stddev(m.REFORMULATION_SEARCHES) as STDDEV_REFORMULATION_SEARCHES
    , stddev(m.TOTAL_SEARCHES) as STDDEV_TOTAL_SEARCHES
    , COALESCE(DIV0NULL(sum(m.REFORM_DIFFERENT_KEYWORD_SEARCHES),visitor_count), 0) as AVG_REFORM_DIFFERENT_KEYWORD_SEARCHES
    , sum(m.REFORM_DIFFERENT_KEYWORD_SEARCHES) as SUM_REFORM_DIFFERENT_KEYWORD_SEARCHES
    , count(distinct m.REFORM_DIFFERENT_KEYWORD_SEARCHES) as COUNT_DISTINCT_REFORM_DIFFERENT_KEYWORD_SEARCHES
    , case when visitor_count > 1 then (sum(power(m.REFORM_DIFFERENT_KEYWORD_SEARCHES,2)) - (visitor_count * power((sum(m.REFORM_DIFFERENT_KEYWORD_SEARCHES) / visitor_count),2))) / (visitor_count - 1) else 0 end  as VARIANCE_REFORM_DIFFERENT_KEYWORD_SEARCHES
    , case when visitor_count > 1 then (sum(m.REFORM_DIFFERENT_KEYWORD_SEARCHES * m.TOTAL_SEARCHES) - (visitor_count * (sum(m.REFORM_DIFFERENT_KEYWORD_SEARCHES) / visitor_count) * (sum(m.TOTAL_SEARCHES) / visitor_count))) / (visitor_count - 1) else 0 end as COV_RE_SEARCH_RATE_DIFFERENT_KEYWORD
    , stddev(m.REFORM_DIFFERENT_KEYWORD_SEARCHES) as STDDEV_REFORM_DIFFERENT_KEYWORD_SEARCHES
    , COALESCE(DIV0NULL(sum(m.AUTOCOMPLETE_SEARCHES),visitor_count), 0) as AVG_AUTOCOMPLETE_SEARCHES
    , sum(m.AUTOCOMPLETE_SEARCHES) as SUM_AUTOCOMPLETE_SEARCHES
    , count(distinct m.AUTOCOMPLETE_SEARCHES) as COUNT_DISTINCT_AUTOCOMPLETE_SEARCHES
    , case when visitor_count > 1 then (sum(power(m.AUTOCOMPLETE_SEARCHES,2)) - (visitor_count * power((sum(m.AUTOCOMPLETE_SEARCHES) / visitor_count),2))) / (visitor_count - 1) else 0 end  as VARIANCE_AUTOCOMPLETE_SEARCHES
    , case when visitor_count > 1 then (sum(m.AUTOCOMPLETE_SEARCHES * m.TOTAL_SEARCHES) - (visitor_count * (sum(m.AUTOCOMPLETE_SEARCHES) / visitor_count) * (sum(m.TOTAL_SEARCHES) / visitor_count))) / (visitor_count - 1) else 0 end as COV_AUTOCOMPLETE_SEARCH_RATE
    , stddev(m.AUTOCOMPLETE_SEARCHES) as STDDEV_AUTOCOMPLETE_SEARCHES
    , COALESCE(DIV0NULL(sum(m.AUTOCOMPLETE_SEARCHES_WITH_PURCHASE),visitor_count), 0) as AVG_AUTOCOMPLETE_SEARCHES_WITH_PURCHASE
    , sum(m.AUTOCOMPLETE_SEARCHES_WITH_PURCHASE) as SUM_AUTOCOMPLETE_SEARCHES_WITH_PURCHASE
    , count(distinct m.AUTOCOMPLETE_SEARCHES_WITH_PURCHASE) as COUNT_DISTINCT_AUTOCOMPLETE_SEARCHES_WITH_PURCHASE
    , case when visitor_count > 1 then (sum(power(m.AUTOCOMPLETE_SEARCHES_WITH_PURCHASE,2)) - (visitor_count * power((sum(m.AUTOCOMPLETE_SEARCHES_WITH_PURCHASE) / visitor_count),2))) / (visitor_count - 1) else 0 end  as VARIANCE_AUTOCOMPLETE_SEARCHES_WITH_PURCHASE
    , case when visitor_count > 1 then (sum(m.AUTOCOMPLETE_SEARCHES_WITH_PURCHASE * m.AUTOCOMPLETE_SEARCHES) - (visitor_count * (sum(m.AUTOCOMPLETE_SEARCHES_WITH_PURCHASE) / visitor_count) * (sum(m.AUTOCOMPLETE_SEARCHES) / visitor_count))) / (visitor_count - 1) else 0 end as COV_AUTOCOMPLETE_SEARCH_CVR
    , stddev(m.AUTOCOMPLETE_SEARCHES_WITH_PURCHASE) as STDDEV_AUTOCOMPLETE_SEARCHES_WITH_PURCHASE
    , COALESCE(DIV0NULL(sum(m.SEARCHES_WITH_PRODUCT_ENGAGEMENT),visitor_count), 0) as AVG_SEARCHES_WITH_PRODUCT_ENGAGEMENT
    , sum(m.SEARCHES_WITH_PRODUCT_ENGAGEMENT) as SUM_SEARCHES_WITH_PRODUCT_ENGAGEMENT
    , count(distinct m.SEARCHES_WITH_PRODUCT_ENGAGEMENT) as COUNT_DISTINCT_SEARCHES_WITH_PRODUCT_ENGAGEMENT
    , case when visitor_count > 1 then (sum(power(m.SEARCHES_WITH_PRODUCT_ENGAGEMENT,2)) - (visitor_count * power((sum(m.SEARCHES_WITH_PRODUCT_ENGAGEMENT) / visitor_count),2))) / (visitor_count - 1) else 0 end  as VARIANCE_SEARCHES_WITH_PRODUCT_ENGAGEMENT
    , case when visitor_count > 1 then (sum(m.SEARCHES_WITH_PRODUCT_ENGAGEMENT * m.TOTAL_SEARCHES) - (visitor_count * (sum(m.SEARCHES_WITH_PRODUCT_ENGAGEMENT) / visitor_count) * (sum(m.TOTAL_SEARCHES) / visitor_count))) / (visitor_count - 1) else 0 end as COV_SEARCH_TERM_CTR
    , stddev(m.SEARCHES_WITH_PRODUCT_ENGAGEMENT) as STDDEV_SEARCHES_WITH_PRODUCT_ENGAGEMENT
    , COALESCE(DIV0NULL(sum(m.CLICK_RECIPROCAL_RANK),visitor_count), 0) as AVG_CLICK_RECIPROCAL_RANK
    , sum(m.CLICK_RECIPROCAL_RANK) as SUM_CLICK_RECIPROCAL_RANK
    , count(distinct m.CLICK_RECIPROCAL_RANK) as COUNT_DISTINCT_CLICK_RECIPROCAL_RANK
    , case when visitor_count > 1 then (sum(power(m.CLICK_RECIPROCAL_RANK,2)) - (visitor_count * power((sum(m.CLICK_RECIPROCAL_RANK) / visitor_count),2))) / (visitor_count - 1) else 0 end  as VARIANCE_CLICK_RECIPROCAL_RANK
    , case when visitor_count > 1 then (sum(m.CLICK_RECIPROCAL_RANK * m.TOTAL_SEARCHES) - (visitor_count * (sum(m.CLICK_RECIPROCAL_RANK) / visitor_count) * (sum(m.TOTAL_SEARCHES) / visitor_count))) / (visitor_count - 1) else 0 end as COV_MEAN_RECIPROCAL_RANK_FOR_CLICK
    , stddev(m.CLICK_RECIPROCAL_RANK) as STDDEV_CLICK_RECIPROCAL_RANK
    , COALESCE(DIV0NULL(sum(m.MULTILEVEL_NDCG),visitor_count), 0) as AVG_MULTILEVEL_NDCG
    , sum(m.MULTILEVEL_NDCG) as SUM_MULTILEVEL_NDCG
    , count(distinct m.MULTILEVEL_NDCG) as COUNT_DISTINCT_MULTILEVEL_NDCG
    , case when visitor_count > 1 then (sum(power(m.MULTILEVEL_NDCG,2)) - (visitor_count * power((sum(m.MULTILEVEL_NDCG) / visitor_count),2))) / (visitor_count - 1) else 0 end  as VARIANCE_MULTILEVEL_NDCG
    , case when visitor_count > 1 then (sum(m.MULTILEVEL_NDCG * m.TOTAL_SEARCHES) - (visitor_count * (sum(m.MULTILEVEL_NDCG) / visitor_count) * (sum(m.TOTAL_SEARCHES) / visitor_count))) / (visitor_count - 1) else 0 end as COV_MULTILEVEL_NDCG
    , stddev(m.MULTILEVEL_NDCG) as STDDEV_MULTILEVEL_NDCG
    , COALESCE(DIV0NULL(sum(m.NULL_RESULT_SEARCHES),visitor_count), 0) as AVG_NULL_RESULT_SEARCHES
    , sum(m.NULL_RESULT_SEARCHES) as SUM_NULL_RESULT_SEARCHES
    , count(distinct m.NULL_RESULT_SEARCHES) as COUNT_DISTINCT_NULL_RESULT_SEARCHES
    , case when visitor_count > 1 then (sum(power(m.NULL_RESULT_SEARCHES,2)) - (visitor_count * power((sum(m.NULL_RESULT_SEARCHES) / visitor_count),2))) / (visitor_count - 1) else 0 end  as VARIANCE_NULL_RESULT_SEARCHES
    , case when visitor_count > 1 then (sum(m.NULL_RESULT_SEARCHES * m.TOTAL_SEARCHES) - (visitor_count * (sum(m.NULL_RESULT_SEARCHES) / visitor_count) * (sum(m.TOTAL_SEARCHES) / visitor_count))) / (visitor_count - 1) else 0 end as COV_NULL_RESULT_RATE
    , stddev(m.NULL_RESULT_SEARCHES) as STDDEV_NULL_RESULT_SEARCHES
    , COALESCE(DIV0NULL(sum(m.SEARCHES_WITH_NO_PRODUCT_ENGAGEMENT),visitor_count), 0) as AVG_SEARCHES_WITH_NO_PRODUCT_ENGAGEMENT
    , sum(m.SEARCHES_WITH_NO_PRODUCT_ENGAGEMENT) as SUM_SEARCHES_WITH_NO_PRODUCT_ENGAGEMENT
    , count(distinct m.SEARCHES_WITH_NO_PRODUCT_ENGAGEMENT) as COUNT_DISTINCT_SEARCHES_WITH_NO_PRODUCT_ENGAGEMENT
    , case when visitor_count > 1 then (sum(power(m.SEARCHES_WITH_NO_PRODUCT_ENGAGEMENT,2)) - (visitor_count * power((sum(m.SEARCHES_WITH_NO_PRODUCT_ENGAGEMENT) / visitor_count),2))) / (visitor_count - 1) else 0 end  as VARIANCE_SEARCHES_WITH_NO_PRODUCT_ENGAGEMENT
    , case when visitor_count > 1 then (sum(m.SEARCHES_WITH_NO_PRODUCT_ENGAGEMENT * m.TOTAL_SEARCHES) - (visitor_count * (sum(m.SEARCHES_WITH_NO_PRODUCT_ENGAGEMENT) / visitor_count) * (sum(m.TOTAL_SEARCHES) / visitor_count))) / (visitor_count - 1) else 0 end as COV_NO_PRODUCT_ENGAGEMENT_RATE
    , stddev(m.SEARCHES_WITH_NO_PRODUCT_ENGAGEMENT) as STDDEV_SEARCHES_WITH_NO_PRODUCT_ENGAGEMENT
    , COALESCE(DIV0NULL(sum(m.EXIT_SEARCHES),visitor_count), 0) as AVG_EXIT_SEARCHES
    , sum(m.EXIT_SEARCHES) as SUM_EXIT_SEARCHES
    , count(distinct m.EXIT_SEARCHES) as COUNT_DISTINCT_EXIT_SEARCHES
    , case when visitor_count > 1 then (sum(power(m.EXIT_SEARCHES,2)) - (visitor_count * power((sum(m.EXIT_SEARCHES) / visitor_count),2))) / (visitor_count - 1) else 0 end  as VARIANCE_EXIT_SEARCHES
    , case when visitor_count > 1 then (sum(m.EXIT_SEARCHES * m.TOTAL_SEARCHES) - (visitor_count * (sum(m.EXIT_SEARCHES) / visitor_count) * (sum(m.TOTAL_SEARCHES) / visitor_count))) / (visitor_count - 1) else 0 end as COV_EXIT_RATE
    , stddev(m.EXIT_SEARCHES) as STDDEV_EXIT_SEARCHES
    , COALESCE(DIV0NULL(sum(m.SEARCHES_WITH_ADDTOCART_CLICK),visitor_count), 0) as AVG_SEARCHES_WITH_ADDTOCART_CLICK
    , sum(m.SEARCHES_WITH_ADDTOCART_CLICK) as SUM_SEARCHES_WITH_ADDTOCART_CLICK
    , count(distinct m.SEARCHES_WITH_ADDTOCART_CLICK) as COUNT_DISTINCT_SEARCHES_WITH_ADDTOCART_CLICK
    , case when visitor_count > 1 then (sum(power(m.SEARCHES_WITH_ADDTOCART_CLICK,2)) - (visitor_count * power((sum(m.SEARCHES_WITH_ADDTOCART_CLICK) / visitor_count),2))) / (visitor_count - 1) else 0 end  as VARIANCE_SEARCHES_WITH_ADDTOCART_CLICK
    , case when visitor_count > 1 then (sum(m.SEARCHES_WITH_ADDTOCART_CLICK * m.TOTAL_SEARCHES) - (visitor_count * (sum(m.SEARCHES_WITH_ADDTOCART_CLICK) / visitor_count) * (sum(m.TOTAL_SEARCHES) / visitor_count))) / (visitor_count - 1) else 0 end as COV_SEARCH_TERM_ATC_RATE
    , stddev(m.SEARCHES_WITH_ADDTOCART_CLICK) as STDDEV_SEARCHES_WITH_ADDTOCART_CLICK
    , COALESCE(DIV0NULL(sum(m.SEARCHES_WITH_PURCHASE),visitor_count), 0) as AVG_SEARCHES_WITH_PURCHASE
    , sum(m.SEARCHES_WITH_PURCHASE) as SUM_SEARCHES_WITH_PURCHASE
    , count(distinct m.SEARCHES_WITH_PURCHASE) as COUNT_DISTINCT_SEARCHES_WITH_PURCHASE
    , case when visitor_count > 1 then (sum(power(m.SEARCHES_WITH_PURCHASE,2)) - (visitor_count * power((sum(m.SEARCHES_WITH_PURCHASE) / visitor_count),2))) / (visitor_count - 1) else 0 end  as VARIANCE_SEARCHES_WITH_PURCHASE
    , case when visitor_count > 1 then (sum(m.SEARCHES_WITH_PURCHASE * m.TOTAL_SEARCHES) - (visitor_count * (sum(m.SEARCHES_WITH_PURCHASE) / visitor_count) * (sum(m.TOTAL_SEARCHES) / visitor_count))) / (visitor_count - 1) else 0 end as COV_SEARCH_TERM_CVR
    , stddev(m.SEARCHES_WITH_PURCHASE) as STDDEV_SEARCHES_WITH_PURCHASE
    , COALESCE(DIV0NULL(sum(m.TOTAL_SEARCH_SESSIONS),visitor_count), 0) as AVG_TOTAL_SEARCH_SESSIONS
    , sum(m.TOTAL_SEARCH_SESSIONS) as SUM_TOTAL_SEARCH_SESSIONS
    , count(distinct m.TOTAL_SEARCH_SESSIONS) as COUNT_DISTINCT_TOTAL_SEARCH_SESSIONS
    , case when visitor_count > 1 then (sum(power(m.TOTAL_SEARCH_SESSIONS,2)) - (visitor_count * power((sum(m.TOTAL_SEARCH_SESSIONS) / visitor_count),2))) / (visitor_count - 1) else 0 end  as VARIANCE_TOTAL_SEARCH_SESSIONS
    , case when visitor_count > 1 then (sum(m.TOTAL_SEARCHES * m.TOTAL_SEARCH_SESSIONS) - (visitor_count * (sum(m.TOTAL_SEARCHES) / visitor_count) * (sum(m.TOTAL_SEARCH_SESSIONS) / visitor_count))) / (visitor_count - 1) else 0 end as COV_SEARCHES_PER_SEARCH_SESSION
    , stddev(m.TOTAL_SEARCH_SESSIONS) as STDDEV_TOTAL_SEARCH_SESSIONS
    , COALESCE(DIV0NULL(sum(m.SEARCHES_WITH_PURCHASE_MULTI_TOUCH),visitor_count), 0) as AVG_SEARCHES_WITH_PURCHASE_MULTI_TOUCH
    , sum(m.SEARCHES_WITH_PURCHASE_MULTI_TOUCH) as SUM_SEARCHES_WITH_PURCHASE_MULTI_TOUCH
    , count(distinct m.SEARCHES_WITH_PURCHASE_MULTI_TOUCH) as COUNT_DISTINCT_SEARCHES_WITH_PURCHASE_MULTI_TOUCH
    , case when visitor_count > 1 then (sum(power(m.SEARCHES_WITH_PURCHASE_MULTI_TOUCH,2)) - (visitor_count * power((sum(m.SEARCHES_WITH_PURCHASE_MULTI_TOUCH) / visitor_count),2))) / (visitor_count - 1) else 0 end  as VARIANCE_SEARCHES_WITH_PURCHASE_MULTI_TOUCH
    , case when visitor_count > 1 then (sum(m.SEARCHES_WITH_PURCHASE_MULTI_TOUCH * m.TOTAL_SEARCHES) - (visitor_count * (sum(m.SEARCHES_WITH_PURCHASE_MULTI_TOUCH) / visitor_count) * (sum(m.TOTAL_SEARCHES) / visitor_count))) / (visitor_count - 1) else 0 end as COV_SEARCH_TERM_CVR_MULTI_TOUCH
    , stddev(m.SEARCHES_WITH_PURCHASE_MULTI_TOUCH) as STDDEV_SEARCHES_WITH_PURCHASE_MULTI_TOUCH
    , COALESCE(DIV0NULL(sum(m.ATTRIBUTED_LAST_TOUCH_REVENUE),visitor_count), 0) as AVG_ATTRIBUTED_LAST_TOUCH_REVENUE
    , sum(m.ATTRIBUTED_LAST_TOUCH_REVENUE) as SUM_ATTRIBUTED_LAST_TOUCH_REVENUE
    , count(distinct m.ATTRIBUTED_LAST_TOUCH_REVENUE) as COUNT_DISTINCT_ATTRIBUTED_LAST_TOUCH_REVENUE
    , case when visitor_count > 1 then (sum(power(m.ATTRIBUTED_LAST_TOUCH_REVENUE,2)) - (visitor_count * power((sum(m.ATTRIBUTED_LAST_TOUCH_REVENUE) / visitor_count),2))) / (visitor_count - 1) else 0 end  as VARIANCE_ATTRIBUTED_LAST_TOUCH_REVENUE
    , case when visitor_count > 1 then (sum(m.ATTRIBUTED_LAST_TOUCH_REVENUE * m.TOTAL_SEARCHES) - (visitor_count * (sum(m.ATTRIBUTED_LAST_TOUCH_REVENUE) / visitor_count) * (sum(m.TOTAL_SEARCHES) / visitor_count))) / (visitor_count - 1) else 0 end as COV_LAST_TOUCH_ATTRIBUTED_REVENUE_PER_SEARCH
    , stddev(m.ATTRIBUTED_LAST_TOUCH_REVENUE) as STDDEV_ATTRIBUTED_LAST_TOUCH_REVENUE
    , COALESCE(DIV0NULL(sum(m.ATTRIBUTED_MULTI_TOUCH_REVENUE),visitor_count), 0) as AVG_ATTRIBUTED_MULTI_TOUCH_REVENUE
    , sum(m.ATTRIBUTED_MULTI_TOUCH_REVENUE) as SUM_ATTRIBUTED_MULTI_TOUCH_REVENUE
    , count(distinct m.ATTRIBUTED_MULTI_TOUCH_REVENUE) as COUNT_DISTINCT_ATTRIBUTED_MULTI_TOUCH_REVENUE
    , case when visitor_count > 1 then (sum(power(m.ATTRIBUTED_MULTI_TOUCH_REVENUE,2)) - (visitor_count * power((sum(m.ATTRIBUTED_MULTI_TOUCH_REVENUE) / visitor_count),2))) / (visitor_count - 1) else 0 end  as VARIANCE_ATTRIBUTED_MULTI_TOUCH_REVENUE
    , case when visitor_count > 1 then (sum(m.ATTRIBUTED_MULTI_TOUCH_REVENUE * m.TOTAL_SEARCHES) - (visitor_count * (sum(m.ATTRIBUTED_MULTI_TOUCH_REVENUE) / visitor_count) * (sum(m.TOTAL_SEARCHES) / visitor_count))) / (visitor_count - 1) else 0 end as COV_MULTI_TOUCH_ATTRIBUTED_REVENUE_PER_SEARCH
    , stddev(m.ATTRIBUTED_MULTI_TOUCH_REVENUE) as STDDEV_ATTRIBUTED_MULTI_TOUCH_REVENUE
    , case when visitor_count > 1 then (sum(m.ATTRIBUTED_MULTI_TOUCH_REVENUE * m.TOTAL_SEARCH_SESSIONS) - (visitor_count * (sum(m.ATTRIBUTED_MULTI_TOUCH_REVENUE) / visitor_count) * (sum(m.TOTAL_SEARCH_SESSIONS) / visitor_count))) / (visitor_count - 1) else 0 end as COV_REVENUE_PER_SEARCH_SESSION
    , COALESCE(DIV0NULL(sum(m.SEARCH_SESSION_WITH_PURCHASE_MULTI_TOUCH),visitor_count), 0) as AVG_SEARCH_SESSION_WITH_PURCHASE_MULTI_TOUCH
    , sum(m.SEARCH_SESSION_WITH_PURCHASE_MULTI_TOUCH) as SUM_SEARCH_SESSION_WITH_PURCHASE_MULTI_TOUCH
    , count(distinct m.SEARCH_SESSION_WITH_PURCHASE_MULTI_TOUCH) as COUNT_DISTINCT_SEARCH_SESSION_WITH_PURCHASE_MULTI_TOUCH
    , case when visitor_count > 1 then (sum(power(m.SEARCH_SESSION_WITH_PURCHASE_MULTI_TOUCH,2)) - (visitor_count * power((sum(m.SEARCH_SESSION_WITH_PURCHASE_MULTI_TOUCH) / visitor_count),2))) / (visitor_count - 1) else 0 end  as VARIANCE_SEARCH_SESSION_WITH_PURCHASE_MULTI_TOUCH
    , case when visitor_count > 1 then (sum(m.SEARCH_SESSION_WITH_PURCHASE_MULTI_TOUCH * m.TOTAL_SEARCH_SESSIONS) - (visitor_count * (sum(m.SEARCH_SESSION_WITH_PURCHASE_MULTI_TOUCH) / visitor_count) * (sum(m.TOTAL_SEARCH_SESSIONS) / visitor_count))) / (visitor_count - 1) else 0 end as COV_SEARCH_SESSION_CVR_MULTI_TOUCH
    , stddev(m.SEARCH_SESSION_WITH_PURCHASE_MULTI_TOUCH) as STDDEV_SEARCH_SESSION_WITH_PURCHASE_MULTI_TOUCH
    , COALESCE(DIV0NULL(sum(m.ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE),visitor_count), 0) as AVG_ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE
    , sum(m.ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE) as SUM_ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE
    , count(distinct m.ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE) as COUNT_DISTINCT_ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE
    , case when visitor_count > 1 then (sum(power(m.ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE,2)) - (visitor_count * power((sum(m.ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE) / visitor_count),2))) / (visitor_count - 1) else 0 end  as VARIANCE_ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE
    , case when visitor_count > 1 then (sum(m.ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE * m.TOTAL_SEARCHES) - (visitor_count * (sum(m.ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE) / visitor_count) * (sum(m.TOTAL_SEARCHES) / visitor_count))) / (visitor_count - 1) else 0 end as COV_ADD_TO_AUTOSHIP_CVR_LAST_TOUCH
    , stddev(m.ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE) as STDDEV_ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE
    , COALESCE(DIV0NULL(sum(m.ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE),visitor_count), 0) as AVG_ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE
    , sum(m.ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE) as SUM_ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE
    , count(distinct m.ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE) as COUNT_DISTINCT_ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE
    , case when visitor_count > 1 then (sum(power(m.ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE,2)) - (visitor_count * power((sum(m.ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE) / visitor_count),2))) / (visitor_count - 1) else 0 end  as VARIANCE_ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE
    , case when visitor_count > 1 then (sum(m.ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE * m.TOTAL_SEARCHES) - (visitor_count * (sum(m.ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE) / visitor_count) * (sum(m.TOTAL_SEARCHES) / visitor_count))) / (visitor_count - 1) else 0 end as COV_ADD_TO_NEW_AUTOSHIP_CVR_LAST_TOUCH
    , stddev(m.ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE) as STDDEV_ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE
    , COALESCE(DIV0NULL(sum(m.ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE),visitor_count), 0) as AVG_ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE
    , sum(m.ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE) as SUM_ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE
    , count(distinct m.ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE) as COUNT_DISTINCT_ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE
    , case when visitor_count > 1 then (sum(power(m.ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE,2)) - (visitor_count * power((sum(m.ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE) / visitor_count),2))) / (visitor_count - 1) else 0 end  as VARIANCE_ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE
    , case when visitor_count > 1 then (sum(m.ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE * m.TOTAL_SEARCHES) - (visitor_count * (sum(m.ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE) / visitor_count) * (sum(m.TOTAL_SEARCHES) / visitor_count))) / (visitor_count - 1) else 0 end as COV_ADD_TO_EXIST_AUTOSHIP_CVR_LAST_TOUCH
    , stddev(m.ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE) as STDDEV_ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE
    , COALESCE(DIV0NULL(sum(m.ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH),visitor_count), 0) as AVG_ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH
    , sum(m.ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH) as SUM_ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH
    , count(distinct m.ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH) as COUNT_DISTINCT_ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH
    , case when visitor_count > 1 then (sum(power(m.ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,2)) - (visitor_count * power((sum(m.ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH) / visitor_count),2))) / (visitor_count - 1) else 0 end  as VARIANCE_ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH
    , case when visitor_count > 1 then (sum(m.ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH * m.TOTAL_SEARCHES) - (visitor_count * (sum(m.ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH) / visitor_count) * (sum(m.TOTAL_SEARCHES) / visitor_count))) / (visitor_count - 1) else 0 end as COV_ADD_TO_AUTOSHIP_CVR_MULTI_TOUCH
    , stddev(m.ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH) as STDDEV_ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH
    , COALESCE(DIV0NULL(sum(m.ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH),visitor_count), 0) as AVG_ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH
    , sum(m.ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH) as SUM_ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH
    , count(distinct m.ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH) as COUNT_DISTINCT_ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH
    , case when visitor_count > 1 then (sum(power(m.ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,2)) - (visitor_count * power((sum(m.ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH) / visitor_count),2))) / (visitor_count - 1) else 0 end  as VARIANCE_ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH
    , case when visitor_count > 1 then (sum(m.ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH * m.TOTAL_SEARCHES) - (visitor_count * (sum(m.ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH) / visitor_count) * (sum(m.TOTAL_SEARCHES) / visitor_count))) / (visitor_count - 1) else 0 end as COV_ADD_TO_NEW_AUTOSHIP_CVR_MULTI_TOUCH
    , stddev(m.ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH) as STDDEV_ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH
    , COALESCE(DIV0NULL(sum(m.ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH),visitor_count), 0) as AVG_ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH
    , sum(m.ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH) as SUM_ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH
    , count(distinct m.ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH) as COUNT_DISTINCT_ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH
    , case when visitor_count > 1 then (sum(power(m.ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,2)) - (visitor_count * power((sum(m.ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH) / visitor_count),2))) / (visitor_count - 1) else 0 end  as VARIANCE_ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH
    , case when visitor_count > 1 then (sum(m.ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH * m.TOTAL_SEARCHES) - (visitor_count * (sum(m.ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH) / visitor_count) * (sum(m.TOTAL_SEARCHES) / visitor_count))) / (visitor_count - 1) else 0 end as COV_ADD_TO_EXIST_AUTOSHIP_CVR_MULTI_TOUCH
    , stddev(m.ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH) as STDDEV_ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH
from tmp_custom_exp_readout_step_1 m
join visitor_counts v on m.data_date = v.data_date AND m.experiment = v.experiment AND m.variation = v.variation
group by $data_date, m.EXPERIMENT, m.VARIATION
;

create or replace  local temp table TEMP_MS_EXP_METRICS_LEVEL_2 as
with
pairwise_json as (
   select a.data_date,
  'ALL' as groupingset_name,
  'discovery_search_metrics.sql' as src_file,
  a.EXPERIMENT,
  a.VARIATION,
  COUNT(DISTINCT a.VARIATION) OVER (PARTITION BY a.EXPERIMENT, a.GROUPINGSET_NAME, a.DATA_DATE) AS variation_cnt,
  DIV0NULL(0.05, COUNT(DISTINCT a.VARIATION) OVER (PARTITION BY a.EXPERIMENT, a.GROUPINGSET_NAME, a.DATA_DATE)) AS SIGNIFICANCE,
  ARRAY_CONSTRUCT(
    OBJECT_CONSTRUCT_KEEP_NULL(
      'metric', 'RE_SEARCH_RATE',
      'metric_type', 'ratio',
      'VISITOR_COUNT', a.visitor_count,
      'CONTROL_VISITOR_COUNT', b.visitor_count,
      'AVG_NUMERATOR', a.AVG_REFORMULATION_SEARCHES,
      'CONTROL_AVG_NUMERATOR', b.AVG_REFORMULATION_SEARCHES,
      'AVG_DENOMINATOR', a.AVG_TOTAL_SEARCHES,
      'CONTROL_AVG_DENOMINATOR', b.AVG_TOTAL_SEARCHES,
      'SUM_NUMERATOR', a.SUM_REFORMULATION_SEARCHES,
      'CONTROL_SUM_NUMERATOR', b.SUM_REFORMULATION_SEARCHES,
      'SUM_DENOMINATOR', a.SUM_TOTAL_SEARCHES,
      'CONTROL_SUM_DENOMINATOR', b.SUM_TOTAL_SEARCHES,
      'COUNT_DISTINCT_NUMERATOR', a.COUNT_DISTINCT_REFORMULATION_SEARCHES,
      'CONTROL_COUNT_DISTINCT_NUMERATOR', b.COUNT_DISTINCT_REFORMULATION_SEARCHES,
      'COUNT_DISTINCT_DENOMINATOR', a.COUNT_DISTINCT_TOTAL_SEARCHES,
      'CONTROL_COUNT_DISTINCT_DENOMINATOR', b.COUNT_DISTINCT_TOTAL_SEARCHES,
      'VARIANCE_NUMERATOR', a.VARIANCE_REFORMULATION_SEARCHES,
      'CONTROL_VARIANCE_NUMERATOR', b.VARIANCE_REFORMULATION_SEARCHES,
      'VARIANCE_DENOMINATOR', a.VARIANCE_TOTAL_SEARCHES,
      'CONTROL_VARIANCE_DENOMINATOR', b.VARIANCE_TOTAL_SEARCHES,
      'STDDEV_NUMERATOR', a.STDDEV_REFORMULATION_SEARCHES,
      'CONTROL_STDDEV_NUMERATOR', b.STDDEV_REFORMULATION_SEARCHES,
      'STDDEV_DENOMINATOR', a.STDDEV_TOTAL_SEARCHES,
      'CONTROL_STDDEV_DENOMINATOR', b.STDDEV_TOTAL_SEARCHES,
      'COV', a.COV_RE_SEARCH_RATE,
      'CONTROL_COV', b.COV_RE_SEARCH_RATE
    ),
    OBJECT_CONSTRUCT_KEEP_NULL(
      'metric', 'RE_SEARCH_RATE_DIFFERENT_KEYWORD',
      'metric_type', 'ratio',
      'VISITOR_COUNT', a.visitor_count,
      'CONTROL_VISITOR_COUNT', b.visitor_count,
      'AVG_NUMERATOR', a.AVG_REFORM_DIFFERENT_KEYWORD_SEARCHES,
      'CONTROL_AVG_NUMERATOR', b.AVG_REFORM_DIFFERENT_KEYWORD_SEARCHES,
      'AVG_DENOMINATOR', a.AVG_TOTAL_SEARCHES,
      'CONTROL_AVG_DENOMINATOR', b.AVG_TOTAL_SEARCHES,
      'SUM_NUMERATOR', a.SUM_REFORM_DIFFERENT_KEYWORD_SEARCHES,
      'CONTROL_SUM_NUMERATOR', b.SUM_REFORM_DIFFERENT_KEYWORD_SEARCHES,
      'SUM_DENOMINATOR', a.SUM_TOTAL_SEARCHES,
      'CONTROL_SUM_DENOMINATOR', b.SUM_TOTAL_SEARCHES,
      'COUNT_DISTINCT_NUMERATOR', a.COUNT_DISTINCT_REFORM_DIFFERENT_KEYWORD_SEARCHES,
      'CONTROL_COUNT_DISTINCT_NUMERATOR', b.COUNT_DISTINCT_REFORM_DIFFERENT_KEYWORD_SEARCHES,
      'COUNT_DISTINCT_DENOMINATOR', a.COUNT_DISTINCT_TOTAL_SEARCHES,
      'CONTROL_COUNT_DISTINCT_DENOMINATOR', b.COUNT_DISTINCT_TOTAL_SEARCHES,
      'VARIANCE_NUMERATOR', a.VARIANCE_REFORM_DIFFERENT_KEYWORD_SEARCHES,
      'CONTROL_VARIANCE_NUMERATOR', b.VARIANCE_REFORM_DIFFERENT_KEYWORD_SEARCHES,
      'VARIANCE_DENOMINATOR', a.VARIANCE_TOTAL_SEARCHES,
      'CONTROL_VARIANCE_DENOMINATOR', b.VARIANCE_TOTAL_SEARCHES,
      'STDDEV_NUMERATOR', a.STDDEV_REFORM_DIFFERENT_KEYWORD_SEARCHES,
      'CONTROL_STDDEV_NUMERATOR', b.STDDEV_REFORM_DIFFERENT_KEYWORD_SEARCHES,
      'STDDEV_DENOMINATOR', a.STDDEV_TOTAL_SEARCHES,
      'CONTROL_STDDEV_DENOMINATOR', b.STDDEV_TOTAL_SEARCHES,
      'COV', a.COV_RE_SEARCH_RATE_DIFFERENT_KEYWORD,
      'CONTROL_COV', b.COV_RE_SEARCH_RATE_DIFFERENT_KEYWORD
    ),
    OBJECT_CONSTRUCT_KEEP_NULL(
      'metric', 'AUTOCOMPLETE_SEARCH_RATE',
      'metric_type', 'ratio',
      'VISITOR_COUNT', a.visitor_count,
      'CONTROL_VISITOR_COUNT', b.visitor_count,
      'AVG_NUMERATOR', a.AVG_AUTOCOMPLETE_SEARCHES,
      'CONTROL_AVG_NUMERATOR', b.AVG_AUTOCOMPLETE_SEARCHES,
      'AVG_DENOMINATOR', a.AVG_TOTAL_SEARCHES,
      'CONTROL_AVG_DENOMINATOR', b.AVG_TOTAL_SEARCHES,
      'SUM_NUMERATOR', a.SUM_AUTOCOMPLETE_SEARCHES,
      'CONTROL_SUM_NUMERATOR', b.SUM_AUTOCOMPLETE_SEARCHES,
      'SUM_DENOMINATOR', a.SUM_TOTAL_SEARCHES,
      'CONTROL_SUM_DENOMINATOR', b.SUM_TOTAL_SEARCHES,
      'COUNT_DISTINCT_NUMERATOR', a.COUNT_DISTINCT_AUTOCOMPLETE_SEARCHES,
      'CONTROL_COUNT_DISTINCT_NUMERATOR', b.COUNT_DISTINCT_AUTOCOMPLETE_SEARCHES,
      'COUNT_DISTINCT_DENOMINATOR', a.COUNT_DISTINCT_TOTAL_SEARCHES,
      'CONTROL_COUNT_DISTINCT_DENOMINATOR', b.COUNT_DISTINCT_TOTAL_SEARCHES,
      'VARIANCE_NUMERATOR', a.VARIANCE_AUTOCOMPLETE_SEARCHES,
      'CONTROL_VARIANCE_NUMERATOR', b.VARIANCE_AUTOCOMPLETE_SEARCHES,
      'VARIANCE_DENOMINATOR', a.VARIANCE_TOTAL_SEARCHES,
      'CONTROL_VARIANCE_DENOMINATOR', b.VARIANCE_TOTAL_SEARCHES,
      'STDDEV_NUMERATOR', a.STDDEV_AUTOCOMPLETE_SEARCHES,
      'CONTROL_STDDEV_NUMERATOR', b.STDDEV_AUTOCOMPLETE_SEARCHES,
      'STDDEV_DENOMINATOR', a.STDDEV_TOTAL_SEARCHES,
      'CONTROL_STDDEV_DENOMINATOR', b.STDDEV_TOTAL_SEARCHES,
      'COV', a.COV_AUTOCOMPLETE_SEARCH_RATE,
      'CONTROL_COV', b.COV_AUTOCOMPLETE_SEARCH_RATE
    ),
    OBJECT_CONSTRUCT_KEEP_NULL(
      'metric', 'AUTOCOMPLETE_SEARCH_CVR',
      'metric_type', 'ratio',
      'VISITOR_COUNT', a.visitor_count,
      'CONTROL_VISITOR_COUNT', b.visitor_count,
      'AVG_NUMERATOR', a.AVG_AUTOCOMPLETE_SEARCHES_WITH_PURCHASE,
      'CONTROL_AVG_NUMERATOR', b.AVG_AUTOCOMPLETE_SEARCHES_WITH_PURCHASE,
      'AVG_DENOMINATOR', a.AVG_AUTOCOMPLETE_SEARCHES,
      'CONTROL_AVG_DENOMINATOR', b.AVG_AUTOCOMPLETE_SEARCHES,
      'SUM_NUMERATOR', a.SUM_AUTOCOMPLETE_SEARCHES_WITH_PURCHASE,
      'CONTROL_SUM_NUMERATOR', b.SUM_AUTOCOMPLETE_SEARCHES_WITH_PURCHASE,
      'SUM_DENOMINATOR', a.SUM_AUTOCOMPLETE_SEARCHES,
      'CONTROL_SUM_DENOMINATOR', b.SUM_AUTOCOMPLETE_SEARCHES,
      'COUNT_DISTINCT_NUMERATOR', a.COUNT_DISTINCT_AUTOCOMPLETE_SEARCHES_WITH_PURCHASE,
      'CONTROL_COUNT_DISTINCT_NUMERATOR', b.COUNT_DISTINCT_AUTOCOMPLETE_SEARCHES_WITH_PURCHASE,
      'COUNT_DISTINCT_DENOMINATOR', a.COUNT_DISTINCT_AUTOCOMPLETE_SEARCHES,
      'CONTROL_COUNT_DISTINCT_DENOMINATOR', b.COUNT_DISTINCT_AUTOCOMPLETE_SEARCHES,
      'VARIANCE_NUMERATOR', a.VARIANCE_AUTOCOMPLETE_SEARCHES_WITH_PURCHASE,
      'CONTROL_VARIANCE_NUMERATOR', b.VARIANCE_AUTOCOMPLETE_SEARCHES_WITH_PURCHASE,
      'VARIANCE_DENOMINATOR', a.VARIANCE_AUTOCOMPLETE_SEARCHES,
      'CONTROL_VARIANCE_DENOMINATOR', b.VARIANCE_AUTOCOMPLETE_SEARCHES,
      'STDDEV_NUMERATOR', a.STDDEV_AUTOCOMPLETE_SEARCHES_WITH_PURCHASE,
      'CONTROL_STDDEV_NUMERATOR', b.STDDEV_AUTOCOMPLETE_SEARCHES_WITH_PURCHASE,
      'STDDEV_DENOMINATOR', a.STDDEV_AUTOCOMPLETE_SEARCHES,
      'CONTROL_STDDEV_DENOMINATOR', b.STDDEV_AUTOCOMPLETE_SEARCHES,
      'COV', a.COV_AUTOCOMPLETE_SEARCH_CVR,
      'CONTROL_COV', b.COV_AUTOCOMPLETE_SEARCH_CVR
    ),
    OBJECT_CONSTRUCT_KEEP_NULL(
      'metric', 'SEARCH_TERM_CTR',
      'metric_type', 'ratio',
      'VISITOR_COUNT', a.visitor_count,
      'CONTROL_VISITOR_COUNT', b.visitor_count,
      'AVG_NUMERATOR', a.AVG_SEARCHES_WITH_PRODUCT_ENGAGEMENT,
      'CONTROL_AVG_NUMERATOR', b.AVG_SEARCHES_WITH_PRODUCT_ENGAGEMENT,
      'AVG_DENOMINATOR', a.AVG_TOTAL_SEARCHES,
      'CONTROL_AVG_DENOMINATOR', b.AVG_TOTAL_SEARCHES,
      'SUM_NUMERATOR', a.SUM_SEARCHES_WITH_PRODUCT_ENGAGEMENT,
      'CONTROL_SUM_NUMERATOR', b.SUM_SEARCHES_WITH_PRODUCT_ENGAGEMENT,
      'SUM_DENOMINATOR', a.SUM_TOTAL_SEARCHES,
      'CONTROL_SUM_DENOMINATOR', b.SUM_TOTAL_SEARCHES,
      'COUNT_DISTINCT_NUMERATOR', a.COUNT_DISTINCT_SEARCHES_WITH_PRODUCT_ENGAGEMENT,
      'CONTROL_COUNT_DISTINCT_NUMERATOR', b.COUNT_DISTINCT_SEARCHES_WITH_PRODUCT_ENGAGEMENT,
      'COUNT_DISTINCT_DENOMINATOR', a.COUNT_DISTINCT_TOTAL_SEARCHES,
      'CONTROL_COUNT_DISTINCT_DENOMINATOR', b.COUNT_DISTINCT_TOTAL_SEARCHES,
      'VARIANCE_NUMERATOR', a.VARIANCE_SEARCHES_WITH_PRODUCT_ENGAGEMENT,
      'CONTROL_VARIANCE_NUMERATOR', b.VARIANCE_SEARCHES_WITH_PRODUCT_ENGAGEMENT,
      'VARIANCE_DENOMINATOR', a.VARIANCE_TOTAL_SEARCHES,
      'CONTROL_VARIANCE_DENOMINATOR', b.VARIANCE_TOTAL_SEARCHES,
      'STDDEV_NUMERATOR', a.STDDEV_SEARCHES_WITH_PRODUCT_ENGAGEMENT,
      'CONTROL_STDDEV_NUMERATOR', b.STDDEV_SEARCHES_WITH_PRODUCT_ENGAGEMENT,
      'STDDEV_DENOMINATOR', a.STDDEV_TOTAL_SEARCHES,
      'CONTROL_STDDEV_DENOMINATOR', b.STDDEV_TOTAL_SEARCHES,
      'COV', a.COV_SEARCH_TERM_CTR,
      'CONTROL_COV', b.COV_SEARCH_TERM_CTR
    ),
    OBJECT_CONSTRUCT_KEEP_NULL(
      'metric', 'MEAN_RECIPROCAL_RANK_FOR_CLICK',
      'metric_type', 'ratio',
      'VISITOR_COUNT', a.visitor_count,
      'CONTROL_VISITOR_COUNT', b.visitor_count,
      'AVG_NUMERATOR', a.AVG_CLICK_RECIPROCAL_RANK,
      'CONTROL_AVG_NUMERATOR', b.AVG_CLICK_RECIPROCAL_RANK,
      'AVG_DENOMINATOR', a.AVG_TOTAL_SEARCHES,
      'CONTROL_AVG_DENOMINATOR', b.AVG_TOTAL_SEARCHES,
      'SUM_NUMERATOR', a.SUM_CLICK_RECIPROCAL_RANK,
      'CONTROL_SUM_NUMERATOR', b.SUM_CLICK_RECIPROCAL_RANK,
      'SUM_DENOMINATOR', a.SUM_TOTAL_SEARCHES,
      'CONTROL_SUM_DENOMINATOR', b.SUM_TOTAL_SEARCHES,
      'COUNT_DISTINCT_NUMERATOR', a.COUNT_DISTINCT_CLICK_RECIPROCAL_RANK,
      'CONTROL_COUNT_DISTINCT_NUMERATOR', b.COUNT_DISTINCT_CLICK_RECIPROCAL_RANK,
      'COUNT_DISTINCT_DENOMINATOR', a.COUNT_DISTINCT_TOTAL_SEARCHES,
      'CONTROL_COUNT_DISTINCT_DENOMINATOR', b.COUNT_DISTINCT_TOTAL_SEARCHES,
      'VARIANCE_NUMERATOR', a.VARIANCE_CLICK_RECIPROCAL_RANK,
      'CONTROL_VARIANCE_NUMERATOR', b.VARIANCE_CLICK_RECIPROCAL_RANK,
      'VARIANCE_DENOMINATOR', a.VARIANCE_TOTAL_SEARCHES,
      'CONTROL_VARIANCE_DENOMINATOR', b.VARIANCE_TOTAL_SEARCHES,
      'STDDEV_NUMERATOR', a.STDDEV_CLICK_RECIPROCAL_RANK,
      'CONTROL_STDDEV_NUMERATOR', b.STDDEV_CLICK_RECIPROCAL_RANK,
      'STDDEV_DENOMINATOR', a.STDDEV_TOTAL_SEARCHES,
      'CONTROL_STDDEV_DENOMINATOR', b.STDDEV_TOTAL_SEARCHES,
      'COV', a.COV_MEAN_RECIPROCAL_RANK_FOR_CLICK,
      'CONTROL_COV', b.COV_MEAN_RECIPROCAL_RANK_FOR_CLICK
    ),
    OBJECT_CONSTRUCT_KEEP_NULL(
      'metric', 'MULTILEVEL_NDCG',
      'metric_type', 'ratio',
      'VISITOR_COUNT', a.visitor_count,
      'CONTROL_VISITOR_COUNT', b.visitor_count,
      'AVG_NUMERATOR', a.AVG_MULTILEVEL_NDCG,
      'CONTROL_AVG_NUMERATOR', b.AVG_MULTILEVEL_NDCG,
      'AVG_DENOMINATOR', a.AVG_TOTAL_SEARCHES,
      'CONTROL_AVG_DENOMINATOR', b.AVG_TOTAL_SEARCHES,
      'SUM_NUMERATOR', a.SUM_MULTILEVEL_NDCG,
      'CONTROL_SUM_NUMERATOR', b.SUM_MULTILEVEL_NDCG,
      'SUM_DENOMINATOR', a.SUM_TOTAL_SEARCHES,
      'CONTROL_SUM_DENOMINATOR', b.SUM_TOTAL_SEARCHES,
      'COUNT_DISTINCT_NUMERATOR', a.COUNT_DISTINCT_MULTILEVEL_NDCG,
      'CONTROL_COUNT_DISTINCT_NUMERATOR', b.COUNT_DISTINCT_MULTILEVEL_NDCG,
      'COUNT_DISTINCT_DENOMINATOR', a.COUNT_DISTINCT_TOTAL_SEARCHES,
      'CONTROL_COUNT_DISTINCT_DENOMINATOR', b.COUNT_DISTINCT_TOTAL_SEARCHES,
      'VARIANCE_NUMERATOR', a.VARIANCE_MULTILEVEL_NDCG,
      'CONTROL_VARIANCE_NUMERATOR', b.VARIANCE_MULTILEVEL_NDCG,
      'VARIANCE_DENOMINATOR', a.VARIANCE_TOTAL_SEARCHES,
      'CONTROL_VARIANCE_DENOMINATOR', b.VARIANCE_TOTAL_SEARCHES,
      'STDDEV_NUMERATOR', a.STDDEV_MULTILEVEL_NDCG,
      'CONTROL_STDDEV_NUMERATOR', b.STDDEV_MULTILEVEL_NDCG,
      'STDDEV_DENOMINATOR', a.STDDEV_TOTAL_SEARCHES,
      'CONTROL_STDDEV_DENOMINATOR', b.STDDEV_TOTAL_SEARCHES,
      'COV', a.COV_MULTILEVEL_NDCG,
      'CONTROL_COV', b.COV_MULTILEVEL_NDCG
    ),
    OBJECT_CONSTRUCT_KEEP_NULL(
      'metric', 'NULL_RESULT_RATE',
      'metric_type', 'ratio',
      'VISITOR_COUNT', a.visitor_count,
      'CONTROL_VISITOR_COUNT', b.visitor_count,
      'AVG_NUMERATOR', a.AVG_NULL_RESULT_SEARCHES,
      'CONTROL_AVG_NUMERATOR', b.AVG_NULL_RESULT_SEARCHES,
      'AVG_DENOMINATOR', a.AVG_TOTAL_SEARCHES,
      'CONTROL_AVG_DENOMINATOR', b.AVG_TOTAL_SEARCHES,
      'SUM_NUMERATOR', a.SUM_NULL_RESULT_SEARCHES,
      'CONTROL_SUM_NUMERATOR', b.SUM_NULL_RESULT_SEARCHES,
      'SUM_DENOMINATOR', a.SUM_TOTAL_SEARCHES,
      'CONTROL_SUM_DENOMINATOR', b.SUM_TOTAL_SEARCHES,
      'COUNT_DISTINCT_NUMERATOR', a.COUNT_DISTINCT_NULL_RESULT_SEARCHES,
      'CONTROL_COUNT_DISTINCT_NUMERATOR', b.COUNT_DISTINCT_NULL_RESULT_SEARCHES,
      'COUNT_DISTINCT_DENOMINATOR', a.COUNT_DISTINCT_TOTAL_SEARCHES,
      'CONTROL_COUNT_DISTINCT_DENOMINATOR', b.COUNT_DISTINCT_TOTAL_SEARCHES,
      'VARIANCE_NUMERATOR', a.VARIANCE_NULL_RESULT_SEARCHES,
      'CONTROL_VARIANCE_NUMERATOR', b.VARIANCE_NULL_RESULT_SEARCHES,
      'VARIANCE_DENOMINATOR', a.VARIANCE_TOTAL_SEARCHES,
      'CONTROL_VARIANCE_DENOMINATOR', b.VARIANCE_TOTAL_SEARCHES,
      'STDDEV_NUMERATOR', a.STDDEV_NULL_RESULT_SEARCHES,
      'CONTROL_STDDEV_NUMERATOR', b.STDDEV_NULL_RESULT_SEARCHES,
      'STDDEV_DENOMINATOR', a.STDDEV_TOTAL_SEARCHES,
      'CONTROL_STDDEV_DENOMINATOR', b.STDDEV_TOTAL_SEARCHES,
      'COV', a.COV_NULL_RESULT_RATE,
      'CONTROL_COV', b.COV_NULL_RESULT_RATE
    ),
    OBJECT_CONSTRUCT_KEEP_NULL(
      'metric', 'NO_PRODUCT_ENGAGEMENT_RATE',
      'metric_type', 'ratio',
      'VISITOR_COUNT', a.visitor_count,
      'CONTROL_VISITOR_COUNT', b.visitor_count,
      'AVG_NUMERATOR', a.AVG_SEARCHES_WITH_NO_PRODUCT_ENGAGEMENT,
      'CONTROL_AVG_NUMERATOR', b.AVG_SEARCHES_WITH_NO_PRODUCT_ENGAGEMENT,
      'AVG_DENOMINATOR', a.AVG_TOTAL_SEARCHES,
      'CONTROL_AVG_DENOMINATOR', b.AVG_TOTAL_SEARCHES,
      'SUM_NUMERATOR', a.SUM_SEARCHES_WITH_NO_PRODUCT_ENGAGEMENT,
      'CONTROL_SUM_NUMERATOR', b.SUM_SEARCHES_WITH_NO_PRODUCT_ENGAGEMENT,
      'SUM_DENOMINATOR', a.SUM_TOTAL_SEARCHES,
      'CONTROL_SUM_DENOMINATOR', b.SUM_TOTAL_SEARCHES,
      'COUNT_DISTINCT_NUMERATOR', a.COUNT_DISTINCT_SEARCHES_WITH_NO_PRODUCT_ENGAGEMENT,
      'CONTROL_COUNT_DISTINCT_NUMERATOR', b.COUNT_DISTINCT_SEARCHES_WITH_NO_PRODUCT_ENGAGEMENT,
      'COUNT_DISTINCT_DENOMINATOR', a.COUNT_DISTINCT_TOTAL_SEARCHES,
      'CONTROL_COUNT_DISTINCT_DENOMINATOR', b.COUNT_DISTINCT_TOTAL_SEARCHES,
      'VARIANCE_NUMERATOR', a.VARIANCE_SEARCHES_WITH_NO_PRODUCT_ENGAGEMENT,
      'CONTROL_VARIANCE_NUMERATOR', b.VARIANCE_SEARCHES_WITH_NO_PRODUCT_ENGAGEMENT,
      'VARIANCE_DENOMINATOR', a.VARIANCE_TOTAL_SEARCHES,
      'CONTROL_VARIANCE_DENOMINATOR', b.VARIANCE_TOTAL_SEARCHES,
      'STDDEV_NUMERATOR', a.STDDEV_SEARCHES_WITH_NO_PRODUCT_ENGAGEMENT,
      'CONTROL_STDDEV_NUMERATOR', b.STDDEV_SEARCHES_WITH_NO_PRODUCT_ENGAGEMENT,
      'STDDEV_DENOMINATOR', a.STDDEV_TOTAL_SEARCHES,
      'CONTROL_STDDEV_DENOMINATOR', b.STDDEV_TOTAL_SEARCHES,
      'COV', a.COV_NO_PRODUCT_ENGAGEMENT_RATE,
      'CONTROL_COV', b.COV_NO_PRODUCT_ENGAGEMENT_RATE
    ),
    OBJECT_CONSTRUCT_KEEP_NULL(
      'metric', 'EXIT_RATE',
      'metric_type', 'ratio',
      'VISITOR_COUNT', a.visitor_count,
      'CONTROL_VISITOR_COUNT', b.visitor_count,
      'AVG_NUMERATOR', a.AVG_EXIT_SEARCHES,
      'CONTROL_AVG_NUMERATOR', b.AVG_EXIT_SEARCHES,
      'AVG_DENOMINATOR', a.AVG_TOTAL_SEARCHES,
      'CONTROL_AVG_DENOMINATOR', b.AVG_TOTAL_SEARCHES,
      'SUM_NUMERATOR', a.SUM_EXIT_SEARCHES,
      'CONTROL_SUM_NUMERATOR', b.SUM_EXIT_SEARCHES,
      'SUM_DENOMINATOR', a.SUM_TOTAL_SEARCHES,
      'CONTROL_SUM_DENOMINATOR', b.SUM_TOTAL_SEARCHES,
      'COUNT_DISTINCT_NUMERATOR', a.COUNT_DISTINCT_EXIT_SEARCHES,
      'CONTROL_COUNT_DISTINCT_NUMERATOR', b.COUNT_DISTINCT_EXIT_SEARCHES,
      'COUNT_DISTINCT_DENOMINATOR', a.COUNT_DISTINCT_TOTAL_SEARCHES,
      'CONTROL_COUNT_DISTINCT_DENOMINATOR', b.COUNT_DISTINCT_TOTAL_SEARCHES,
      'VARIANCE_NUMERATOR', a.VARIANCE_EXIT_SEARCHES,
      'CONTROL_VARIANCE_NUMERATOR', b.VARIANCE_EXIT_SEARCHES,
      'VARIANCE_DENOMINATOR', a.VARIANCE_TOTAL_SEARCHES,
      'CONTROL_VARIANCE_DENOMINATOR', b.VARIANCE_TOTAL_SEARCHES,
      'STDDEV_NUMERATOR', a.STDDEV_EXIT_SEARCHES,
      'CONTROL_STDDEV_NUMERATOR', b.STDDEV_EXIT_SEARCHES,
      'STDDEV_DENOMINATOR', a.STDDEV_TOTAL_SEARCHES,
      'CONTROL_STDDEV_DENOMINATOR', b.STDDEV_TOTAL_SEARCHES,
      'COV', a.COV_EXIT_RATE,
      'CONTROL_COV', b.COV_EXIT_RATE
    ),
    OBJECT_CONSTRUCT_KEEP_NULL(
      'metric', 'SEARCH_TERM_ATC_RATE',
      'metric_type', 'ratio',
      'VISITOR_COUNT', a.visitor_count,
      'CONTROL_VISITOR_COUNT', b.visitor_count,
      'AVG_NUMERATOR', a.AVG_SEARCHES_WITH_ADDTOCART_CLICK,
      'CONTROL_AVG_NUMERATOR', b.AVG_SEARCHES_WITH_ADDTOCART_CLICK,
      'AVG_DENOMINATOR', a.AVG_TOTAL_SEARCHES,
      'CONTROL_AVG_DENOMINATOR', b.AVG_TOTAL_SEARCHES,
      'SUM_NUMERATOR', a.SUM_SEARCHES_WITH_ADDTOCART_CLICK,
      'CONTROL_SUM_NUMERATOR', b.SUM_SEARCHES_WITH_ADDTOCART_CLICK,
      'SUM_DENOMINATOR', a.SUM_TOTAL_SEARCHES,
      'CONTROL_SUM_DENOMINATOR', b.SUM_TOTAL_SEARCHES,
      'COUNT_DISTINCT_NUMERATOR', a.COUNT_DISTINCT_SEARCHES_WITH_ADDTOCART_CLICK,
      'CONTROL_COUNT_DISTINCT_NUMERATOR', b.COUNT_DISTINCT_SEARCHES_WITH_ADDTOCART_CLICK,
      'COUNT_DISTINCT_DENOMINATOR', a.COUNT_DISTINCT_TOTAL_SEARCHES,
      'CONTROL_COUNT_DISTINCT_DENOMINATOR', b.COUNT_DISTINCT_TOTAL_SEARCHES,
      'VARIANCE_NUMERATOR', a.VARIANCE_SEARCHES_WITH_ADDTOCART_CLICK,
      'CONTROL_VARIANCE_NUMERATOR', b.VARIANCE_SEARCHES_WITH_ADDTOCART_CLICK,
      'VARIANCE_DENOMINATOR', a.VARIANCE_TOTAL_SEARCHES,
      'CONTROL_VARIANCE_DENOMINATOR', b.VARIANCE_TOTAL_SEARCHES,
      'STDDEV_NUMERATOR', a.STDDEV_SEARCHES_WITH_ADDTOCART_CLICK,
      'CONTROL_STDDEV_NUMERATOR', b.STDDEV_SEARCHES_WITH_ADDTOCART_CLICK,
      'STDDEV_DENOMINATOR', a.STDDEV_TOTAL_SEARCHES,
      'CONTROL_STDDEV_DENOMINATOR', b.STDDEV_TOTAL_SEARCHES,
      'COV', a.COV_SEARCH_TERM_ATC_RATE,
      'CONTROL_COV', b.COV_SEARCH_TERM_ATC_RATE
    ),
    OBJECT_CONSTRUCT_KEEP_NULL(
      'metric', 'SEARCH_TERM_CVR',
      'metric_type', 'ratio',
      'VISITOR_COUNT', a.visitor_count,
      'CONTROL_VISITOR_COUNT', b.visitor_count,
      'AVG_NUMERATOR', a.AVG_SEARCHES_WITH_PURCHASE,
      'CONTROL_AVG_NUMERATOR', b.AVG_SEARCHES_WITH_PURCHASE,
      'AVG_DENOMINATOR', a.AVG_TOTAL_SEARCHES,
      'CONTROL_AVG_DENOMINATOR', b.AVG_TOTAL_SEARCHES,
      'SUM_NUMERATOR', a.SUM_SEARCHES_WITH_PURCHASE,
      'CONTROL_SUM_NUMERATOR', b.SUM_SEARCHES_WITH_PURCHASE,
      'SUM_DENOMINATOR', a.SUM_TOTAL_SEARCHES,
      'CONTROL_SUM_DENOMINATOR', b.SUM_TOTAL_SEARCHES,
      'COUNT_DISTINCT_NUMERATOR', a.COUNT_DISTINCT_SEARCHES_WITH_PURCHASE,
      'CONTROL_COUNT_DISTINCT_NUMERATOR', b.COUNT_DISTINCT_SEARCHES_WITH_PURCHASE,
      'COUNT_DISTINCT_DENOMINATOR', a.COUNT_DISTINCT_TOTAL_SEARCHES,
      'CONTROL_COUNT_DISTINCT_DENOMINATOR', b.COUNT_DISTINCT_TOTAL_SEARCHES,
      'VARIANCE_NUMERATOR', a.VARIANCE_SEARCHES_WITH_PURCHASE,
      'CONTROL_VARIANCE_NUMERATOR', b.VARIANCE_SEARCHES_WITH_PURCHASE,
      'VARIANCE_DENOMINATOR', a.VARIANCE_TOTAL_SEARCHES,
      'CONTROL_VARIANCE_DENOMINATOR', b.VARIANCE_TOTAL_SEARCHES,
      'STDDEV_NUMERATOR', a.STDDEV_SEARCHES_WITH_PURCHASE,
      'CONTROL_STDDEV_NUMERATOR', b.STDDEV_SEARCHES_WITH_PURCHASE,
      'STDDEV_DENOMINATOR', a.STDDEV_TOTAL_SEARCHES,
      'CONTROL_STDDEV_DENOMINATOR', b.STDDEV_TOTAL_SEARCHES,
      'COV', a.COV_SEARCH_TERM_CVR,
      'CONTROL_COV', b.COV_SEARCH_TERM_CVR
    ),
    OBJECT_CONSTRUCT_KEEP_NULL(
      'metric', 'SEARCHES_PER_SEARCH_SESSION',
      'metric_type', 'ratio',
      'VISITOR_COUNT', a.visitor_count,
      'CONTROL_VISITOR_COUNT', b.visitor_count,
      'AVG_NUMERATOR', a.AVG_TOTAL_SEARCHES,
      'CONTROL_AVG_NUMERATOR', b.AVG_TOTAL_SEARCHES,
      'AVG_DENOMINATOR', a.AVG_TOTAL_SEARCH_SESSIONS,
      'CONTROL_AVG_DENOMINATOR', b.AVG_TOTAL_SEARCH_SESSIONS,
      'SUM_NUMERATOR', a.SUM_TOTAL_SEARCHES,
      'CONTROL_SUM_NUMERATOR', b.SUM_TOTAL_SEARCHES,
      'SUM_DENOMINATOR', a.SUM_TOTAL_SEARCH_SESSIONS,
      'CONTROL_SUM_DENOMINATOR', b.SUM_TOTAL_SEARCH_SESSIONS,
      'COUNT_DISTINCT_NUMERATOR', a.COUNT_DISTINCT_TOTAL_SEARCHES,
      'CONTROL_COUNT_DISTINCT_NUMERATOR', b.COUNT_DISTINCT_TOTAL_SEARCHES,
      'COUNT_DISTINCT_DENOMINATOR', a.COUNT_DISTINCT_TOTAL_SEARCH_SESSIONS,
      'CONTROL_COUNT_DISTINCT_DENOMINATOR', b.COUNT_DISTINCT_TOTAL_SEARCH_SESSIONS,
      'VARIANCE_NUMERATOR', a.VARIANCE_TOTAL_SEARCHES,
      'CONTROL_VARIANCE_NUMERATOR', b.VARIANCE_TOTAL_SEARCHES,
      'VARIANCE_DENOMINATOR', a.VARIANCE_TOTAL_SEARCH_SESSIONS,
      'CONTROL_VARIANCE_DENOMINATOR', b.VARIANCE_TOTAL_SEARCH_SESSIONS,
      'STDDEV_NUMERATOR', a.STDDEV_TOTAL_SEARCHES,
      'CONTROL_STDDEV_NUMERATOR', b.STDDEV_TOTAL_SEARCHES,
      'STDDEV_DENOMINATOR', a.STDDEV_TOTAL_SEARCH_SESSIONS,
      'CONTROL_STDDEV_DENOMINATOR', b.STDDEV_TOTAL_SEARCH_SESSIONS,
      'COV', a.COV_SEARCHES_PER_SEARCH_SESSION,
      'CONTROL_COV', b.COV_SEARCHES_PER_SEARCH_SESSION
    ),
    OBJECT_CONSTRUCT_KEEP_NULL(
      'metric', 'SEARCH_TERM_CVR_MULTI_TOUCH',
      'metric_type', 'ratio',
      'VISITOR_COUNT', a.visitor_count,
      'CONTROL_VISITOR_COUNT', b.visitor_count,
      'AVG_NUMERATOR', a.AVG_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'CONTROL_AVG_NUMERATOR', b.AVG_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'AVG_DENOMINATOR', a.AVG_TOTAL_SEARCHES,
      'CONTROL_AVG_DENOMINATOR', b.AVG_TOTAL_SEARCHES,
      'SUM_NUMERATOR', a.SUM_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'CONTROL_SUM_NUMERATOR', b.SUM_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'SUM_DENOMINATOR', a.SUM_TOTAL_SEARCHES,
      'CONTROL_SUM_DENOMINATOR', b.SUM_TOTAL_SEARCHES,
      'COUNT_DISTINCT_NUMERATOR', a.COUNT_DISTINCT_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'CONTROL_COUNT_DISTINCT_NUMERATOR', b.COUNT_DISTINCT_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'COUNT_DISTINCT_DENOMINATOR', a.COUNT_DISTINCT_TOTAL_SEARCHES,
      'CONTROL_COUNT_DISTINCT_DENOMINATOR', b.COUNT_DISTINCT_TOTAL_SEARCHES,
      'VARIANCE_NUMERATOR', a.VARIANCE_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'CONTROL_VARIANCE_NUMERATOR', b.VARIANCE_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'VARIANCE_DENOMINATOR', a.VARIANCE_TOTAL_SEARCHES,
      'CONTROL_VARIANCE_DENOMINATOR', b.VARIANCE_TOTAL_SEARCHES,
      'STDDEV_NUMERATOR', a.STDDEV_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'CONTROL_STDDEV_NUMERATOR', b.STDDEV_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'STDDEV_DENOMINATOR', a.STDDEV_TOTAL_SEARCHES,
      'CONTROL_STDDEV_DENOMINATOR', b.STDDEV_TOTAL_SEARCHES,
      'COV', a.COV_SEARCH_TERM_CVR_MULTI_TOUCH,
      'CONTROL_COV', b.COV_SEARCH_TERM_CVR_MULTI_TOUCH
    ),
    OBJECT_CONSTRUCT_KEEP_NULL(
      'metric', 'LAST_TOUCH_ATTRIBUTED_REVENUE_PER_SEARCH',
      'metric_type', 'ratio',
      'VISITOR_COUNT', a.visitor_count,
      'CONTROL_VISITOR_COUNT', b.visitor_count,
      'AVG_NUMERATOR', a.AVG_ATTRIBUTED_LAST_TOUCH_REVENUE,
      'CONTROL_AVG_NUMERATOR', b.AVG_ATTRIBUTED_LAST_TOUCH_REVENUE,
      'AVG_DENOMINATOR', a.AVG_TOTAL_SEARCHES,
      'CONTROL_AVG_DENOMINATOR', b.AVG_TOTAL_SEARCHES,
      'SUM_NUMERATOR', a.SUM_ATTRIBUTED_LAST_TOUCH_REVENUE,
      'CONTROL_SUM_NUMERATOR', b.SUM_ATTRIBUTED_LAST_TOUCH_REVENUE,
      'SUM_DENOMINATOR', a.SUM_TOTAL_SEARCHES,
      'CONTROL_SUM_DENOMINATOR', b.SUM_TOTAL_SEARCHES,
      'COUNT_DISTINCT_NUMERATOR', a.COUNT_DISTINCT_ATTRIBUTED_LAST_TOUCH_REVENUE,
      'CONTROL_COUNT_DISTINCT_NUMERATOR', b.COUNT_DISTINCT_ATTRIBUTED_LAST_TOUCH_REVENUE,
      'COUNT_DISTINCT_DENOMINATOR', a.COUNT_DISTINCT_TOTAL_SEARCHES,
      'CONTROL_COUNT_DISTINCT_DENOMINATOR', b.COUNT_DISTINCT_TOTAL_SEARCHES,
      'VARIANCE_NUMERATOR', a.VARIANCE_ATTRIBUTED_LAST_TOUCH_REVENUE,
      'CONTROL_VARIANCE_NUMERATOR', b.VARIANCE_ATTRIBUTED_LAST_TOUCH_REVENUE,
      'VARIANCE_DENOMINATOR', a.VARIANCE_TOTAL_SEARCHES,
      'CONTROL_VARIANCE_DENOMINATOR', b.VARIANCE_TOTAL_SEARCHES,
      'STDDEV_NUMERATOR', a.STDDEV_ATTRIBUTED_LAST_TOUCH_REVENUE,
      'CONTROL_STDDEV_NUMERATOR', b.STDDEV_ATTRIBUTED_LAST_TOUCH_REVENUE,
      'STDDEV_DENOMINATOR', a.STDDEV_TOTAL_SEARCHES,
      'CONTROL_STDDEV_DENOMINATOR', b.STDDEV_TOTAL_SEARCHES,
      'COV', a.COV_LAST_TOUCH_ATTRIBUTED_REVENUE_PER_SEARCH,
      'CONTROL_COV', b.COV_LAST_TOUCH_ATTRIBUTED_REVENUE_PER_SEARCH
    ),
    OBJECT_CONSTRUCT_KEEP_NULL(
      'metric', 'MULTI_TOUCH_ATTRIBUTED_REVENUE_PER_SEARCH',
      'metric_type', 'ratio',
      'VISITOR_COUNT', a.visitor_count,
      'CONTROL_VISITOR_COUNT', b.visitor_count,
      'AVG_NUMERATOR', a.AVG_ATTRIBUTED_MULTI_TOUCH_REVENUE,
      'CONTROL_AVG_NUMERATOR', b.AVG_ATTRIBUTED_MULTI_TOUCH_REVENUE,
      'AVG_DENOMINATOR', a.AVG_TOTAL_SEARCHES,
      'CONTROL_AVG_DENOMINATOR', b.AVG_TOTAL_SEARCHES,
      'SUM_NUMERATOR', a.SUM_ATTRIBUTED_MULTI_TOUCH_REVENUE,
      'CONTROL_SUM_NUMERATOR', b.SUM_ATTRIBUTED_MULTI_TOUCH_REVENUE,
      'SUM_DENOMINATOR', a.SUM_TOTAL_SEARCHES,
      'CONTROL_SUM_DENOMINATOR', b.SUM_TOTAL_SEARCHES,
      'COUNT_DISTINCT_NUMERATOR', a.COUNT_DISTINCT_ATTRIBUTED_MULTI_TOUCH_REVENUE,
      'CONTROL_COUNT_DISTINCT_NUMERATOR', b.COUNT_DISTINCT_ATTRIBUTED_MULTI_TOUCH_REVENUE,
      'COUNT_DISTINCT_DENOMINATOR', a.COUNT_DISTINCT_TOTAL_SEARCHES,
      'CONTROL_COUNT_DISTINCT_DENOMINATOR', b.COUNT_DISTINCT_TOTAL_SEARCHES,
      'VARIANCE_NUMERATOR', a.VARIANCE_ATTRIBUTED_MULTI_TOUCH_REVENUE,
      'CONTROL_VARIANCE_NUMERATOR', b.VARIANCE_ATTRIBUTED_MULTI_TOUCH_REVENUE,
      'VARIANCE_DENOMINATOR', a.VARIANCE_TOTAL_SEARCHES,
      'CONTROL_VARIANCE_DENOMINATOR', b.VARIANCE_TOTAL_SEARCHES,
      'STDDEV_NUMERATOR', a.STDDEV_ATTRIBUTED_MULTI_TOUCH_REVENUE,
      'CONTROL_STDDEV_NUMERATOR', b.STDDEV_ATTRIBUTED_MULTI_TOUCH_REVENUE,
      'STDDEV_DENOMINATOR', a.STDDEV_TOTAL_SEARCHES,
      'CONTROL_STDDEV_DENOMINATOR', b.STDDEV_TOTAL_SEARCHES,
      'COV', a.COV_MULTI_TOUCH_ATTRIBUTED_REVENUE_PER_SEARCH,
      'CONTROL_COV', b.COV_MULTI_TOUCH_ATTRIBUTED_REVENUE_PER_SEARCH
    ),
    OBJECT_CONSTRUCT_KEEP_NULL(
      'metric', 'REVENUE_PER_SEARCH_SESSION',
      'metric_type', 'ratio',
      'VISITOR_COUNT', a.visitor_count,
      'CONTROL_VISITOR_COUNT', b.visitor_count,
      'AVG_NUMERATOR', a.AVG_ATTRIBUTED_MULTI_TOUCH_REVENUE,
      'CONTROL_AVG_NUMERATOR', b.AVG_ATTRIBUTED_MULTI_TOUCH_REVENUE,
      'AVG_DENOMINATOR', a.AVG_TOTAL_SEARCH_SESSIONS,
      'CONTROL_AVG_DENOMINATOR', b.AVG_TOTAL_SEARCH_SESSIONS,
      'SUM_NUMERATOR', a.SUM_ATTRIBUTED_MULTI_TOUCH_REVENUE,
      'CONTROL_SUM_NUMERATOR', b.SUM_ATTRIBUTED_MULTI_TOUCH_REVENUE,
      'SUM_DENOMINATOR', a.SUM_TOTAL_SEARCH_SESSIONS,
      'CONTROL_SUM_DENOMINATOR', b.SUM_TOTAL_SEARCH_SESSIONS,
      'COUNT_DISTINCT_NUMERATOR', a.COUNT_DISTINCT_ATTRIBUTED_MULTI_TOUCH_REVENUE,
      'CONTROL_COUNT_DISTINCT_NUMERATOR', b.COUNT_DISTINCT_ATTRIBUTED_MULTI_TOUCH_REVENUE,
      'COUNT_DISTINCT_DENOMINATOR', a.COUNT_DISTINCT_TOTAL_SEARCH_SESSIONS,
      'CONTROL_COUNT_DISTINCT_DENOMINATOR', b.COUNT_DISTINCT_TOTAL_SEARCH_SESSIONS,
      'VARIANCE_NUMERATOR', a.VARIANCE_ATTRIBUTED_MULTI_TOUCH_REVENUE,
      'CONTROL_VARIANCE_NUMERATOR', b.VARIANCE_ATTRIBUTED_MULTI_TOUCH_REVENUE,
      'VARIANCE_DENOMINATOR', a.VARIANCE_TOTAL_SEARCH_SESSIONS,
      'CONTROL_VARIANCE_DENOMINATOR', b.VARIANCE_TOTAL_SEARCH_SESSIONS,
      'STDDEV_NUMERATOR', a.STDDEV_ATTRIBUTED_MULTI_TOUCH_REVENUE,
      'CONTROL_STDDEV_NUMERATOR', b.STDDEV_ATTRIBUTED_MULTI_TOUCH_REVENUE,
      'STDDEV_DENOMINATOR', a.STDDEV_TOTAL_SEARCH_SESSIONS,
      'CONTROL_STDDEV_DENOMINATOR', b.STDDEV_TOTAL_SEARCH_SESSIONS,
      'COV', a.COV_REVENUE_PER_SEARCH_SESSION,
      'CONTROL_COV', b.COV_REVENUE_PER_SEARCH_SESSION
    ),
    OBJECT_CONSTRUCT_KEEP_NULL(
      'metric', 'SEARCH_SESSION_CVR_MULTI_TOUCH',
      'metric_type', 'ratio',
      'VISITOR_COUNT', a.visitor_count,
      'CONTROL_VISITOR_COUNT', b.visitor_count,
      'AVG_NUMERATOR', a.AVG_SEARCH_SESSION_WITH_PURCHASE_MULTI_TOUCH,
      'CONTROL_AVG_NUMERATOR', b.AVG_SEARCH_SESSION_WITH_PURCHASE_MULTI_TOUCH,
      'AVG_DENOMINATOR', a.AVG_TOTAL_SEARCH_SESSIONS,
      'CONTROL_AVG_DENOMINATOR', b.AVG_TOTAL_SEARCH_SESSIONS,
      'SUM_NUMERATOR', a.SUM_SEARCH_SESSION_WITH_PURCHASE_MULTI_TOUCH,
      'CONTROL_SUM_NUMERATOR', b.SUM_SEARCH_SESSION_WITH_PURCHASE_MULTI_TOUCH,
      'SUM_DENOMINATOR', a.SUM_TOTAL_SEARCH_SESSIONS,
      'CONTROL_SUM_DENOMINATOR', b.SUM_TOTAL_SEARCH_SESSIONS,
      'COUNT_DISTINCT_NUMERATOR', a.COUNT_DISTINCT_SEARCH_SESSION_WITH_PURCHASE_MULTI_TOUCH,
      'CONTROL_COUNT_DISTINCT_NUMERATOR', b.COUNT_DISTINCT_SEARCH_SESSION_WITH_PURCHASE_MULTI_TOUCH,
      'COUNT_DISTINCT_DENOMINATOR', a.COUNT_DISTINCT_TOTAL_SEARCH_SESSIONS,
      'CONTROL_COUNT_DISTINCT_DENOMINATOR', b.COUNT_DISTINCT_TOTAL_SEARCH_SESSIONS,
      'VARIANCE_NUMERATOR', a.VARIANCE_SEARCH_SESSION_WITH_PURCHASE_MULTI_TOUCH,
      'CONTROL_VARIANCE_NUMERATOR', b.VARIANCE_SEARCH_SESSION_WITH_PURCHASE_MULTI_TOUCH,
      'VARIANCE_DENOMINATOR', a.VARIANCE_TOTAL_SEARCH_SESSIONS,
      'CONTROL_VARIANCE_DENOMINATOR', b.VARIANCE_TOTAL_SEARCH_SESSIONS,
      'STDDEV_NUMERATOR', a.STDDEV_SEARCH_SESSION_WITH_PURCHASE_MULTI_TOUCH,
      'CONTROL_STDDEV_NUMERATOR', b.STDDEV_SEARCH_SESSION_WITH_PURCHASE_MULTI_TOUCH,
      'STDDEV_DENOMINATOR', a.STDDEV_TOTAL_SEARCH_SESSIONS,
      'CONTROL_STDDEV_DENOMINATOR', b.STDDEV_TOTAL_SEARCH_SESSIONS,
      'COV', a.COV_SEARCH_SESSION_CVR_MULTI_TOUCH,
      'CONTROL_COV', b.COV_SEARCH_SESSION_CVR_MULTI_TOUCH
    ),
    OBJECT_CONSTRUCT_KEEP_NULL(
      'metric', 'ADD_TO_AUTOSHIP_CVR_LAST_TOUCH',
      'metric_type', 'ratio',
      'VISITOR_COUNT', a.visitor_count,
      'CONTROL_VISITOR_COUNT', b.visitor_count,
      'AVG_NUMERATOR', a.AVG_ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE,
      'CONTROL_AVG_NUMERATOR', b.AVG_ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE,
      'AVG_DENOMINATOR', a.AVG_TOTAL_SEARCHES,
      'CONTROL_AVG_DENOMINATOR', b.AVG_TOTAL_SEARCHES,
      'SUM_NUMERATOR', a.SUM_ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE,
      'CONTROL_SUM_NUMERATOR', b.SUM_ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE,
      'SUM_DENOMINATOR', a.SUM_TOTAL_SEARCHES,
      'CONTROL_SUM_DENOMINATOR', b.SUM_TOTAL_SEARCHES,
      'COUNT_DISTINCT_NUMERATOR', a.COUNT_DISTINCT_ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE,
      'CONTROL_COUNT_DISTINCT_NUMERATOR', b.COUNT_DISTINCT_ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE,
      'COUNT_DISTINCT_DENOMINATOR', a.COUNT_DISTINCT_TOTAL_SEARCHES,
      'CONTROL_COUNT_DISTINCT_DENOMINATOR', b.COUNT_DISTINCT_TOTAL_SEARCHES,
      'VARIANCE_NUMERATOR', a.VARIANCE_ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE,
      'CONTROL_VARIANCE_NUMERATOR', b.VARIANCE_ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE,
      'VARIANCE_DENOMINATOR', a.VARIANCE_TOTAL_SEARCHES,
      'CONTROL_VARIANCE_DENOMINATOR', b.VARIANCE_TOTAL_SEARCHES,
      'STDDEV_NUMERATOR', a.STDDEV_ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE,
      'CONTROL_STDDEV_NUMERATOR', b.STDDEV_ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE,
      'STDDEV_DENOMINATOR', a.STDDEV_TOTAL_SEARCHES,
      'CONTROL_STDDEV_DENOMINATOR', b.STDDEV_TOTAL_SEARCHES,
      'COV', a.COV_ADD_TO_AUTOSHIP_CVR_LAST_TOUCH,
      'CONTROL_COV', b.COV_ADD_TO_AUTOSHIP_CVR_LAST_TOUCH
    ),
    OBJECT_CONSTRUCT_KEEP_NULL(
      'metric', 'ADD_TO_NEW_AUTOSHIP_CVR_LAST_TOUCH',
      'metric_type', 'ratio',
      'VISITOR_COUNT', a.visitor_count,
      'CONTROL_VISITOR_COUNT', b.visitor_count,
      'AVG_NUMERATOR', a.AVG_ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE,
      'CONTROL_AVG_NUMERATOR', b.AVG_ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE,
      'AVG_DENOMINATOR', a.AVG_TOTAL_SEARCHES,
      'CONTROL_AVG_DENOMINATOR', b.AVG_TOTAL_SEARCHES,
      'SUM_NUMERATOR', a.SUM_ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE,
      'CONTROL_SUM_NUMERATOR', b.SUM_ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE,
      'SUM_DENOMINATOR', a.SUM_TOTAL_SEARCHES,
      'CONTROL_SUM_DENOMINATOR', b.SUM_TOTAL_SEARCHES,
      'COUNT_DISTINCT_NUMERATOR', a.COUNT_DISTINCT_ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE,
      'CONTROL_COUNT_DISTINCT_NUMERATOR', b.COUNT_DISTINCT_ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE,
      'COUNT_DISTINCT_DENOMINATOR', a.COUNT_DISTINCT_TOTAL_SEARCHES,
      'CONTROL_COUNT_DISTINCT_DENOMINATOR', b.COUNT_DISTINCT_TOTAL_SEARCHES,
      'VARIANCE_NUMERATOR', a.VARIANCE_ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE,
      'CONTROL_VARIANCE_NUMERATOR', b.VARIANCE_ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE,
      'VARIANCE_DENOMINATOR', a.VARIANCE_TOTAL_SEARCHES,
      'CONTROL_VARIANCE_DENOMINATOR', b.VARIANCE_TOTAL_SEARCHES,
      'STDDEV_NUMERATOR', a.STDDEV_ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE,
      'CONTROL_STDDEV_NUMERATOR', b.STDDEV_ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE,
      'STDDEV_DENOMINATOR', a.STDDEV_TOTAL_SEARCHES,
      'CONTROL_STDDEV_DENOMINATOR', b.STDDEV_TOTAL_SEARCHES,
      'COV', a.COV_ADD_TO_NEW_AUTOSHIP_CVR_LAST_TOUCH,
      'CONTROL_COV', b.COV_ADD_TO_NEW_AUTOSHIP_CVR_LAST_TOUCH
    ),
    OBJECT_CONSTRUCT_KEEP_NULL(
      'metric', 'ADD_TO_EXIST_AUTOSHIP_CVR_LAST_TOUCH',
      'metric_type', 'ratio',
      'VISITOR_COUNT', a.visitor_count,
      'CONTROL_VISITOR_COUNT', b.visitor_count,
      'AVG_NUMERATOR', a.AVG_ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE,
      'CONTROL_AVG_NUMERATOR', b.AVG_ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE,
      'AVG_DENOMINATOR', a.AVG_TOTAL_SEARCHES,
      'CONTROL_AVG_DENOMINATOR', b.AVG_TOTAL_SEARCHES,
      'SUM_NUMERATOR', a.SUM_ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE,
      'CONTROL_SUM_NUMERATOR', b.SUM_ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE,
      'SUM_DENOMINATOR', a.SUM_TOTAL_SEARCHES,
      'CONTROL_SUM_DENOMINATOR', b.SUM_TOTAL_SEARCHES,
      'COUNT_DISTINCT_NUMERATOR', a.COUNT_DISTINCT_ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE,
      'CONTROL_COUNT_DISTINCT_NUMERATOR', b.COUNT_DISTINCT_ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE,
      'COUNT_DISTINCT_DENOMINATOR', a.COUNT_DISTINCT_TOTAL_SEARCHES,
      'CONTROL_COUNT_DISTINCT_DENOMINATOR', b.COUNT_DISTINCT_TOTAL_SEARCHES,
      'VARIANCE_NUMERATOR', a.VARIANCE_ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE,
      'CONTROL_VARIANCE_NUMERATOR', b.VARIANCE_ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE,
      'VARIANCE_DENOMINATOR', a.VARIANCE_TOTAL_SEARCHES,
      'CONTROL_VARIANCE_DENOMINATOR', b.VARIANCE_TOTAL_SEARCHES,
      'STDDEV_NUMERATOR', a.STDDEV_ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE,
      'CONTROL_STDDEV_NUMERATOR', b.STDDEV_ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE,
      'STDDEV_DENOMINATOR', a.STDDEV_TOTAL_SEARCHES,
      'CONTROL_STDDEV_DENOMINATOR', b.STDDEV_TOTAL_SEARCHES,
      'COV', a.COV_ADD_TO_EXIST_AUTOSHIP_CVR_LAST_TOUCH,
      'CONTROL_COV', b.COV_ADD_TO_EXIST_AUTOSHIP_CVR_LAST_TOUCH
    ),
    OBJECT_CONSTRUCT_KEEP_NULL(
      'metric', 'ADD_TO_AUTOSHIP_CVR_MULTI_TOUCH',
      'metric_type', 'ratio',
      'VISITOR_COUNT', a.visitor_count,
      'CONTROL_VISITOR_COUNT', b.visitor_count,
      'AVG_NUMERATOR', a.AVG_ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'CONTROL_AVG_NUMERATOR', b.AVG_ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'AVG_DENOMINATOR', a.AVG_TOTAL_SEARCHES,
      'CONTROL_AVG_DENOMINATOR', b.AVG_TOTAL_SEARCHES,
      'SUM_NUMERATOR', a.SUM_ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'CONTROL_SUM_NUMERATOR', b.SUM_ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'SUM_DENOMINATOR', a.SUM_TOTAL_SEARCHES,
      'CONTROL_SUM_DENOMINATOR', b.SUM_TOTAL_SEARCHES,
      'COUNT_DISTINCT_NUMERATOR', a.COUNT_DISTINCT_ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'CONTROL_COUNT_DISTINCT_NUMERATOR', b.COUNT_DISTINCT_ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'COUNT_DISTINCT_DENOMINATOR', a.COUNT_DISTINCT_TOTAL_SEARCHES,
      'CONTROL_COUNT_DISTINCT_DENOMINATOR', b.COUNT_DISTINCT_TOTAL_SEARCHES,
      'VARIANCE_NUMERATOR', a.VARIANCE_ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'CONTROL_VARIANCE_NUMERATOR', b.VARIANCE_ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'VARIANCE_DENOMINATOR', a.VARIANCE_TOTAL_SEARCHES,
      'CONTROL_VARIANCE_DENOMINATOR', b.VARIANCE_TOTAL_SEARCHES,
      'STDDEV_NUMERATOR', a.STDDEV_ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'CONTROL_STDDEV_NUMERATOR', b.STDDEV_ADDTOAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'STDDEV_DENOMINATOR', a.STDDEV_TOTAL_SEARCHES,
      'CONTROL_STDDEV_DENOMINATOR', b.STDDEV_TOTAL_SEARCHES,
      'COV', a.COV_ADD_TO_AUTOSHIP_CVR_MULTI_TOUCH,
      'CONTROL_COV', b.COV_ADD_TO_AUTOSHIP_CVR_MULTI_TOUCH
    ),
    OBJECT_CONSTRUCT_KEEP_NULL(
      'metric', 'ADD_TO_NEW_AUTOSHIP_CVR_MULTI_TOUCH',
      'metric_type', 'ratio',
      'VISITOR_COUNT', a.visitor_count,
      'CONTROL_VISITOR_COUNT', b.visitor_count,
      'AVG_NUMERATOR', a.AVG_ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'CONTROL_AVG_NUMERATOR', b.AVG_ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'AVG_DENOMINATOR', a.AVG_TOTAL_SEARCHES,
      'CONTROL_AVG_DENOMINATOR', b.AVG_TOTAL_SEARCHES,
      'SUM_NUMERATOR', a.SUM_ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'CONTROL_SUM_NUMERATOR', b.SUM_ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'SUM_DENOMINATOR', a.SUM_TOTAL_SEARCHES,
      'CONTROL_SUM_DENOMINATOR', b.SUM_TOTAL_SEARCHES,
      'COUNT_DISTINCT_NUMERATOR', a.COUNT_DISTINCT_ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'CONTROL_COUNT_DISTINCT_NUMERATOR', b.COUNT_DISTINCT_ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'COUNT_DISTINCT_DENOMINATOR', a.COUNT_DISTINCT_TOTAL_SEARCHES,
      'CONTROL_COUNT_DISTINCT_DENOMINATOR', b.COUNT_DISTINCT_TOTAL_SEARCHES,
      'VARIANCE_NUMERATOR', a.VARIANCE_ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'CONTROL_VARIANCE_NUMERATOR', b.VARIANCE_ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'VARIANCE_DENOMINATOR', a.VARIANCE_TOTAL_SEARCHES,
      'CONTROL_VARIANCE_DENOMINATOR', b.VARIANCE_TOTAL_SEARCHES,
      'STDDEV_NUMERATOR', a.STDDEV_ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'CONTROL_STDDEV_NUMERATOR', b.STDDEV_ADDTONEWAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'STDDEV_DENOMINATOR', a.STDDEV_TOTAL_SEARCHES,
      'CONTROL_STDDEV_DENOMINATOR', b.STDDEV_TOTAL_SEARCHES,
      'COV', a.COV_ADD_TO_NEW_AUTOSHIP_CVR_MULTI_TOUCH,
      'CONTROL_COV', b.COV_ADD_TO_NEW_AUTOSHIP_CVR_MULTI_TOUCH
    ),
    OBJECT_CONSTRUCT_KEEP_NULL(
      'metric', 'ADD_TO_EXIST_AUTOSHIP_CVR_MULTI_TOUCH',
      'metric_type', 'ratio',
      'VISITOR_COUNT', a.visitor_count,
      'CONTROL_VISITOR_COUNT', b.visitor_count,
      'AVG_NUMERATOR', a.AVG_ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'CONTROL_AVG_NUMERATOR', b.AVG_ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'AVG_DENOMINATOR', a.AVG_TOTAL_SEARCHES,
      'CONTROL_AVG_DENOMINATOR', b.AVG_TOTAL_SEARCHES,
      'SUM_NUMERATOR', a.SUM_ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'CONTROL_SUM_NUMERATOR', b.SUM_ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'SUM_DENOMINATOR', a.SUM_TOTAL_SEARCHES,
      'CONTROL_SUM_DENOMINATOR', b.SUM_TOTAL_SEARCHES,
      'COUNT_DISTINCT_NUMERATOR', a.COUNT_DISTINCT_ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'CONTROL_COUNT_DISTINCT_NUMERATOR', b.COUNT_DISTINCT_ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'COUNT_DISTINCT_DENOMINATOR', a.COUNT_DISTINCT_TOTAL_SEARCHES,
      'CONTROL_COUNT_DISTINCT_DENOMINATOR', b.COUNT_DISTINCT_TOTAL_SEARCHES,
      'VARIANCE_NUMERATOR', a.VARIANCE_ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'CONTROL_VARIANCE_NUMERATOR', b.VARIANCE_ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'VARIANCE_DENOMINATOR', a.VARIANCE_TOTAL_SEARCHES,
      'CONTROL_VARIANCE_DENOMINATOR', b.VARIANCE_TOTAL_SEARCHES,
      'STDDEV_NUMERATOR', a.STDDEV_ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'CONTROL_STDDEV_NUMERATOR', b.STDDEV_ADDTOEXISTAUTOSHIP_SEARCHES_WITH_PURCHASE_MULTI_TOUCH,
      'STDDEV_DENOMINATOR', a.STDDEV_TOTAL_SEARCHES,
      'CONTROL_STDDEV_DENOMINATOR', b.STDDEV_TOTAL_SEARCHES,
      'COV', a.COV_ADD_TO_EXIST_AUTOSHIP_CVR_MULTI_TOUCH,
      'CONTROL_COV', b.COV_ADD_TO_EXIST_AUTOSHIP_CVR_MULTI_TOUCH
    )
  ) AS metrics_array
from TEMP_TEST_METRICS_level_1 a, TEMP_TEST_METRICS_level_1 b
where a.EXPERIMENT = b.EXPERIMENT AND lower(a.VARIATION) NOT IN ('control', 'false','holdout','quarterly') AND lower(b.VARIATION) IN ('control', 'false','holdout','quarterly')
)
select
  t.data_date,
  t.groupingset_name,
  t.src_file,
  t.EXPERIMENT,
  t.VARIATION,
  t.variation_cnt,
  t.SIGNIFICANCE,
  metric.value:AVG_DENOMINATOR::FLOAT AS avg_denominator,
  metric.value:AVG_NUMERATOR::FLOAT AS avg_numerator,
  metric.value:CONTROL_AVG_DENOMINATOR::FLOAT AS control_avg_denominator,
  metric.value:CONTROL_AVG_NUMERATOR::FLOAT AS control_avg_numerator,
  metric.value:CONTROL_COUNT_DISTINCT_DENOMINATOR::INTEGER AS control_count_distinct_denominator,
  metric.value:CONTROL_COUNT_DISTINCT_NUMERATOR::INTEGER AS control_count_distinct_numerator,
  metric.value:CONTROL_COV::FLOAT AS control_cov,
  metric.value:CONTROL_STDDEV_DENOMINATOR::FLOAT AS control_stddev_denominator,
  metric.value:CONTROL_STDDEV_NUMERATOR::FLOAT AS control_stddev_numerator,
  metric.value:CONTROL_SUM_DENOMINATOR::FLOAT AS control_sum_denominator,
  metric.value:CONTROL_SUM_NUMERATOR::FLOAT AS control_sum_numerator,
  metric.value:CONTROL_VARIANCE_DENOMINATOR::FLOAT AS control_variance_denominator,
  metric.value:CONTROL_VARIANCE_NUMERATOR::FLOAT AS control_variance_numerator,
  metric.value:CONTROL_VISITOR_COUNT::INTEGER AS control_visitor_count,
  metric.value:COUNT_DISTINCT_DENOMINATOR::INTEGER AS count_distinct_denominator,
  metric.value:COUNT_DISTINCT_NUMERATOR::INTEGER AS count_distinct_numerator,
  metric.value:COV::FLOAT AS cov,
  metric.value:STDDEV_DENOMINATOR::FLOAT AS stddev_denominator,
  metric.value:STDDEV_NUMERATOR::FLOAT AS stddev_numerator,
  metric.value:SUM_DENOMINATOR::FLOAT AS sum_denominator,
  metric.value:SUM_NUMERATOR::FLOAT AS sum_numerator,
  metric.value:VARIANCE_DENOMINATOR::FLOAT AS variance_denominator,
  metric.value:VARIANCE_NUMERATOR::FLOAT AS variance_numerator,
  metric.value:VISITOR_COUNT::INTEGER AS visitor_count,
  metric.value:metric::STRING AS metric_name,
  metric.value:metric_type::STRING AS metric_type
from pairwise_json t,
  LATERAL FLATTEN(input => t.metrics_array) AS metric
;


create or replace local temp table ms_exp_results_raw as
with exp_config as (
    -- Get GST config from experiment metadata
    SELECT
        g.EXPERIMENT_NAME,
        COALESCE(g.NUM_OF_CHECKPOINTS, 1) AS NUM_OF_CHECKPOINTS,
        COALESCE(g.SEQUENTIAL_OPTION, FALSE) AS SEQUENTIAL_OPTION,
        g.TEST_DURATION,
        (g.TEST_DURATION * 7) + 1 AS TOTAL_TEST_DAYS,
        d.START_DATE
    FROM BT_SITE_ANALYTICS.EXPLT_EXPERIMENT_METADATA g
    LEFT JOIN ECOM_SANDBOX.EXP_DETAILS d
        ON UPPER(g.EXPERIMENT_NAME) = UPPER(d.EXPERIMENT_NAME)
    WHERE g.TEST_DURATION IS NOT NULL
      AND g.TEST_DURATION > 0
      and g.experiment_name = '2026_04_DISCOVERY_SEARCH_REDIRECT_REMOVALS'
),

gst_function as (
select 'full' AS LOAD_TYPE,
    'ALL' AS METRIC_PROPERTIES,
    'ALL' AS METRIC_PROPERTY_VALUES,
    'ALL' AS ENTITY_PROPERTIES,
    'ALL' AS ENTITY_PROPERTY_VALUES,
    *,
CASE
                WHEN e.SEQUENTIAL_OPTION = TRUE
                     AND e.TOTAL_TEST_DAYS IS NOT NULL
                     AND e.TOTAL_TEST_DAYS > 0
                     AND (CASE
                             WHEN e.TOTAL_TEST_DAYS IS NOT NULL AND e.TOTAL_TEST_DAYS > 0 AND e.START_DATE IS NOT NULL
                             THEN LEAST(DATEDIFF('day', e.START_DATE, $data_date)::FLOAT / e.TOTAL_TEST_DAYS, 1.0)
                             ELSE NULL
                          END) IS NOT NULL
                THEN e.NUM_OF_CHECKPOINTS
                ELSE NULL
            END  NUM_CHECKPOINTS,
            CASE
                WHEN e.SEQUENTIAL_OPTION = TRUE
                     AND e.TOTAL_TEST_DAYS IS NOT NULL
                     AND e.TOTAL_TEST_DAYS > 0
                     AND (CASE
                             WHEN e.TOTAL_TEST_DAYS IS NOT NULL AND e.TOTAL_TEST_DAYS > 0 AND e.START_DATE IS NOT NULL
                             THEN LEAST(DATEDIFF('day', e.START_DATE, $data_date)::FLOAT / e.TOTAL_TEST_DAYS, 1.0)
                             ELSE NULL
                          END) IS NOT NULL
                THEN (CASE
                         WHEN e.TOTAL_TEST_DAYS IS NOT NULL AND e.TOTAL_TEST_DAYS > 0 AND e.START_DATE IS NOT NULL
                         THEN LEAST(DATEDIFF('day', e.START_DATE, $data_date)::FLOAT / e.TOTAL_TEST_DAYS, 1.0)
                         ELSE NULL
                      END)
                ELSE NULL
            END  INFO_FRACTION_INPUT
FROM TEMP_MS_EXP_METRICS_LEVEL_2 m
    LEFT JOIN exp_config e ON UPPER(m.EXPERIMENT) = UPPER(e.EXPERIMENT_NAME)
    WHERE m.DATA_DATE = $data_date)

, results as (
    SELECT m.* EXCLUDE (METRIC_PROPERTIES),
        case when m.METRIC_PROPERTIES = 'PRODUCT_MERCH_CLASSIFICATION1' then 'MC1'
             when m.METRIC_PROPERTIES = 'PRODUCT_MERCH_CLASSIFICATION1,PRODUCT_MERCH_CLASSIFICATION2' then 'MC1,MC2'
        else m.METRIC_PROPERTIES end as METRIC_PROPERTIES,
        ms_calc_delta_ttest_hx(
            m.METRIC_TYPE,
            m.CONTROL_AVG_NUMERATOR,
            m.CONTROL_AVG_DENOMINATOR,
            m.CONTROL_VARIANCE_NUMERATOR,
            m.CONTROL_VARIANCE_DENOMINATOR,
            m.CONTROL_COV,
            m.CONTROL_SUM_NUMERATOR,
            m.CONTROL_SUM_DENOMINATOR,
            m.AVG_NUMERATOR,
            m.AVG_DENOMINATOR,
            m.VARIANCE_NUMERATOR,
            m.VARIANCE_DENOMINATOR,
            m.COV,
            m.SUM_NUMERATOR,
            m.SUM_DENOMINATOR,
            m.CONTROL_VISITOR_COUNT,
            m.VISITOR_COUNT,
            m.SIGNIFICANCE,
            NUM_CHECKPOINTS,
            INFO_FRACTION_INPUT
        )  metric_results
    FROM gst_function m )

select *,
  -- Fixed-horizon results (always present)
  metric_results:"control_mean"::FLOAT AS control_mean,
  metric_results:"variant_mean"::FLOAT AS variant_mean,
  metric_results:"control_var"::FLOAT AS control_var,
  metric_results:"variant_var"::FLOAT AS variant_var,
  metric_results:"delta"::FLOAT AS delta,
  metric_results:"p_value"::FLOAT AS p_value,
  metric_results:"z_score"::FLOAT AS z_score,
  metric_results:"upper_ci"::FLOAT AS upper_ci,
  metric_results:"lower_ci"::FLOAT AS lower_ci,
  -- GST results (always populated when SEQUENTIAL_OPTION = TRUE and GST parameters provided)
  metric_results:"checkpoint_k"::INTEGER AS checkpoint_k,
  metric_results:"info_fraction"::FLOAT AS info_fraction,
  metric_results:"z_critical_gst"::FLOAT AS z_critical_gst,
  metric_results:"upper_ci_gst"::FLOAT AS upper_ci_gst,
  metric_results:"lower_ci_gst"::FLOAT AS lower_ci_gst,
  metric_results:"significance_gst"::FLOAT AS significance_gst,
--   metric_results:"decision_gst"::STRING AS decision_gst,
  -- metric_results:"rejected_gst"::INTEGER::BOOLEAN AS rejected_gst
from results
;

create or replace local temp table ms_exp_results_final as
WITH input_data AS (
    -- Replace this with your actual table/query that contains p_values
    SELECT
        data_date,
        p_value, -- made up values
        experiment, -- Grouping columns as needed
        metric_name,
        groupingset_name,
        variation,
        ENTITY_PROPERTIES,
        ENTITY_PROPERTY_VALUES,
        METRIC_PROPERTIES,
        METRIC_PROPERTY_VALUES
    FROM ms_exp_results_raw
    where groupingset_name <> 'ALL'
        and p_value IS NOT NULL  -- Filter out null p-values
),
-- Step 1: Calculate FDR level (Q) based on number of tests per group
group_stats AS (
    SELECT
        experiment,
        metric_name,
        groupingset_name,
        COUNT(*) as m,  -- Number of valid p-values
        CASE
            WHEN COUNT(*) <= 4 THEN 0.08
            WHEN COUNT(*) < 8 THEN 0.12
            ELSE 0.25
        END as q
    FROM input_data
    GROUP BY experiment, metric_name, groupingset_name
),

-- Step 2: Rank p-values within each group
ranked_data AS (
    SELECT
        i.*,
        g.m,
        g.q,
        ROW_NUMBER() OVER (
            PARTITION BY i.experiment, i.metric_name, i.groupingset_name
            ORDER BY i.p_value
        ) as rank_within_group
    FROM input_data i
    JOIN group_stats g ON
        i.experiment = g.experiment AND
        i.metric_name = g.metric_name AND
        i.groupingset_name = g.groupingset_name
),

-- Step 3: Calculate BH critical values
bh_critical_calc AS (
    SELECT
        *,
        (rank_within_group::FLOAT / m) * q as bh_critical,
        CASE
            WHEN p_value <= (rank_within_group::FLOAT / m) * q THEN TRUE
            ELSE FALSE
        END as bh_rejected
    FROM ranked_data
),

-- Step 4: Find the maximum index where p_value <= bh_critical
max_rejected_rank AS (
    SELECT
        experiment,
        metric_name,
        groupingset_name,
        MAX(CASE WHEN bh_rejected THEN rank_within_group ELSE 0 END) as max_rejected_rank
    FROM bh_critical_calc
    GROUP BY experiment, metric_name, groupingset_name
),

-- Step 5: Determine final rejection status and decision
final_results AS (
    SELECT
        b.*,
        CASE
            WHEN b.rank_within_group <= m.max_rejected_rank THEN 'CONCLUSIVE'
            ELSE 'INCONCLUSIVE'
        END as bh_decision
    FROM bh_critical_calc b
    JOIN max_rejected_rank m ON
        b.experiment = m.experiment AND
        b.metric_name = m.metric_name AND
        b.groupingset_name = m.groupingset_name
)

-- Final output
SELECT
    a.* ,
    bh_critical,
    bh_rejected,
    bh_decision,
    case when a.p_value is null then 'NA'
         when a.groupingset_name = 'ALL' and a.p_value <= significance and delta > 0 then 'POSITIVE'
         when a.groupingset_name = 'ALL' and a.p_value <= significance and DELTA < 0 then 'NEGATIVE'
         when a.groupingset_name = 'ALL' and a.p_value > significance then 'INCONCLUSIVE'
         when a.groupingset_name <> 'ALL' and bh_decision = 'CONCLUSIVE' and DELTA > 0 then 'POSITIVE'
         when a.groupingset_name <> 'ALL' and bh_decision = 'CONCLUSIVE' and DELTA < 0 then 'NEGATIVE'
         when a.groupingset_name <> 'ALL' and bh_decision <> 'CONCLUSIVE' then 'INCONCLUSIVE' end as decision,
    case when a.p_value is null then 'NA'
         when a.groupingset_name = 'ALL' and a.p_value <= significance_gst and delta > 0 then 'POSITIVE'
         when a.groupingset_name = 'ALL' and a.p_value <= significance_gst and DELTA < 0 then 'NEGATIVE'
         when a.groupingset_name = 'ALL' and a.p_value > significance_gst then 'INCONCLUSIVE'
         when a.groupingset_name <> 'ALL' THEN NULL
        end as decision_gst
FROM ms_exp_results_raw a
    left join final_results b on
        a.experiment = b.experiment AND
        a.variation = b.variation AND
        a.metric_name = b.metric_name AND
        a.groupingset_name = b.groupingset_name AND
        a.entity_properties = b.entity_properties and
        a.entity_property_values = b.entity_property_values and
        a.metric_properties = b.metric_properties and
        a.metric_property_values = b.metric_property_values
where a.data_date = $data_date
;

select
experiment,
variation,
metric_name,
control_visitor_count,
visitor_count as variant_visitor_count,
control_mean,
variant_mean,
delta,
lower_ci,
upper_ci,
p_value,
decision
from MS_EXP_RESULTS_FINAL
limit 100
;
